.coveragerc
it's fine to test that abstract methods are in fact abstract (so we can leave our current tests), but we should not require this.
=> don't require coverage for abstract methods

src/nsrt_learning.py, src/structs.py
This change allows the type checking to occur with both usages of Atom construction:
`pred([obj1])`
`Lifted/GroundAtom(pred, [obj1])`
whereas previously it was only occurring with the former.
=> move type check for Atom construction

src/approaches/grammar_search_invention_approach.py, tests/approaches/test_grammar_search_invention_approach.py
I found this bug in investigating for Painting why `IsWet,IsDry` weren't getting selected when they are manually proposed (after ablation). After this fix, they are selected as expected.
When counting true positives and false positives, we should be looking at segments, not individual transitions within segments. The way that this issue was manifesting was that transitions within segments that had no change at the symbolic level were being counted as "true positives" for an operator that has empty effects. That operator was only arising for the empty candidate predicate set, so that empty set was getting a better score than the set containing `IsWet,IsDry`.
=> fix subtle bug in grammar approach

src/nsrt_learning.py, tests/test_nsrt_learning.py
in the case where options are known, we should use the parameterizedoption (and not just the option vars) when unifying in nsrt learning.
=> fix to nsrt learning unify

src/approaches/grammar_search_invention_approach.py, src/approaches/interactive_learning_approach.py, src/sampler_learning.py, src/utils.py, tests/test_nsrt_learning.py, tests/test_utils.py
it's confusing to allow duplicates in operator/nsrt parameters but not within predicates. I want to purge `allow_duplicates=False`.
what led me down this path was a weird binary predicate being learned by the grammar approach in blocks. after digging for a long time, I realized that the predicate was basically acting as `neq` to enforce that operator parameters were different. I want to avoid similar misadventures in the future.
`allow_duplicates=True` is also consistent with standard first-order logic semantics. and we can always capture the same behavior by introducing an explicit `neq` predicate.
I verified that oracle and nsrt_learning still work as expected for cover, blocks, and painting.
=> always allow duplicates

src/approaches/oracle_approach.py, src/envs/cover.py
Adds a robot as a parameter to the ground truth operators for multistep-cover and updates the holding predicate to check both the block and the robot state. After this change, the learned operators through nsrt_learning have the robot as one of their parameters. This is important for option learning. Our learned options need to be able to access the robot state, which can only be done if the learned operators have the robot as a parameter.
=> Add robot as another parameter to ground truth operators.

src/envs/cover.py, src/settings.py, tests/envs/test_cover.py
This allows for flexibility in defining variable step policies in cover_multistep_options because the Pick() and Place() ground truth option policies now clip the low-level-action by the bounds of the action space. If we want policies that take more steps to go from point to point, we can reduce the limits of the action space.
=> Clip cover_multistep_options's option policies with limits of action space. 

src/approaches/oracle_approach.py, src/envs/__init__.py, src/envs/repeated_nextto.py, src/settings.py, tests/approaches/test_oracle_approach.py, tests/envs/test_base_env.py, tests/envs/test_repeated_nextto.py
Toy environment for isolating the problem of a robot being next to potentially differing numbers of things as it moves around an environment. Currently, both planning and learning work only because we have set the threshold for being next to an object to be very low, such that whp the robot is only next to one object at any given time. Increasing this `nextto_thresh = 0.02` threshold would quickly break planning (and learning).
closes #141
=> repeated NextTo env

src/approaches/random_options_approach.py, src/nsrt_learning.py, src/planning.py, src/structs.py, tests/test_utils.py
It's a bit strange that DefaultOption and DefaultOptionModel were separate conceptual ideas. So, doing a simple renaming to make DummyOption sound more similar to DummyOptionModel, which are the same conceptual idea.
=> rename DefaultOption -> DummyOption

src/approaches/grammar_search_invention_approach.py, src/planning.py, src/settings.py, src/utils.py, tests/test_utils.py
hmax is significantly worse in cover, blocks, and painting than hadd, so we don't want to make it the default. but in the playroom domain, hmax can succeed where hadd completely fails. so it's good to give ourselves the option to toggle.
=> hmax heuristic

src/envs/painting.py
This change allows 0.75 coming from the halving_constant_generator to work as a correct implementation of the OnTable predicate. Reasoning:
pose_y is in the range [-10.1, 2.95] which is the table_lb and the shelf_ub respectively. With a constant of 0.75, we get (2.95+10.1)*0.75-10.1 = -0.3125, so with this change, using `obj.pose_y <= -0.3125` as a predicate would represent OnTable.
=> small update to painting env

src/planning.py, src/structs.py, tests/test_structs.py
currently we modify ground NSRTs in-place in the failure discovery part of planning, even though ground NSRTs are frozen. @czeng6 has started encountering issues with this, so this PR is meant to fix the hack.
=> do not modify frozen groundnsrts with notcausesfailure

src/settings.py
Significantly better empirical results on painting. Across 13 seeds on painting with all ablations, `hff_lookahead_depth1` scores an average of 22.7/50, while `hff_lookahead_depth0` scores an average of 34/50. More results on 5 different seeds:
with depth1:
```
TEST_TASKS_SOLVED TEST_TASKS_TOTAL  TOTAL_TEST_TIME       TOTAL_TIME  NUM_SEEDS
ENV             APPROACH                 EXCLUDED_PREDICATES
blocks          grammar_search_invention all                     34.40 (17.87)     50.00 (0.00)  179.71 (174.36)  375.01 (181.59)          5
none                     43.80 (8.41)     50.00 (0.00)    72.65 (76.55)   212.09 (91.40)          5
cover           grammar_search_invention all                      48.80 (1.64)     50.00 (0.00)    13.07 (16.01)   226.89 (52.53)          5
none …
```
=> change score function to hff_lookahead_depth0

analysis/analyze_supercloud_experiments.py, mypy.ini, requirements.txt, src/approaches/nsrt_learning_approach.py, src/main.py, src/sampler_learning.py, src/settings.py, src/structs.py, src/torch_models.py, tests/approaches/test_nsrt_learning_approach.py, tests/test_structs.py
Implement oracle samplers for nsrt_learning pipeline by matching to
ground truth NSRTs in oracle_approach.py. We assert that every ground
truth NSRT must match a learned operator (but not the other way around,
since the pipeline could easily learn extra operators that are unimportant).
Works for cover and blocks, but not for painting because learned operators
don't exactly match ground truth ones.
Switched from pickle to dill because samplers defined in
oracle_approach.py are local functions, which cannot be pickled.
Verified that saving/loading work properly in all cases.
closes #246
=> oracle samplers

src/approaches/grammar_search_invention_approach.py, src/utils.py, tests/approaches/test_grammar_search_invention_approach.py, tests/test_utils.py
realized that pyperplan facts are actually strings, not tuples. this wasn't an issue for hmax/hadd/hff but led to an error for lmcut.
=> add support for other pyperplan heuristics

src/utils.py, tests/test_utils.py
because both env.simulate and option policies are deterministic
=> terminate option execution immediately if it's stuck

src/approaches/oracle_approach.py, src/envs/playroom.py, tests/approaches/test_oracle_approach.py, tests/envs/test_playroom.py
changes implemented to make nsrt learning work:
- make sure for each option, all option vars are used somewhere (either in policy or initiable fnc)
- make sure that each "move transition" by the robot can only be explained by one option -- so now there are 3 different move options, each with a different and more specific policy for movement
- simulator no longer allows the robot to move in ways that the oracle operators do not allow for (e.g. transitioning from region 1 directly to region 3)
- got rid of “robot must be facing x to interact with x” requirement in simulator b/c this made sampling for pick, stack, putontable too hard
=> Playroom nsrt learning

src/planning.py, tests/test_planning.py
Two line edit, 100 line test, lol. @tomsilver note that we don't have to sort `objects` because all the grounding utils methods eventually use `get_object_combinations`, which sorts the objects.
=> planning determinism + test

.github/workflows/predicators.yml
https://stackoverflow.com/questions/70663523/the-unauthenticated-git-protocol-on-port-9418-is-no-longer-supported
=> fix mypy github action install

analysis/grammar_search_analysis.py, src/approaches/grammar_search_invention_approach.py, src/planning.py, tests/test_planning.py
ground the NSRTs only once per task, rather than on every call to `task_plan`. this seems to be a 2-3x speedup (based on running the analysis script before vs after).
=> low-hanging optimizations for exact lookahead

analysis/grammar_search_analysis.py, src/approaches/base_approach.py, src/approaches/grammar_search_invention_approach.py, src/approaches/interactive_learning_approach.py, src/approaches/iterative_invention_approach.py, src/approaches/nsrt_learning_approach.py, src/main.py, src/settings.py, src/structs.py, tests/approaches/test_base_approach.py, tests/approaches/test_grammar_search_invention_approach.py, tests/approaches/test_interactive_approach.py, tests/approaches/test_nsrt_learning_approach.py
A simple code quality change here. Passing train_tasks into
learn_from_offline_dataset is a relic from the past, when we didn't have
our demonstration trajectories annotated with goals. All the information
in train_tasks is already contained in the Dataset object itself.
Instead of:
```
for task in train_tasks:
print(task.init, task.goal)
```
one can do:
```
for traj in dataset:
if not traj.is_demo:
continue
print(traj.states[0], traj.goal)
```
=> don't give approaches redundant train_tasks argument

src/main.py, tests/test_main.py
Catch approach failures, specifically OptionPlanExhausted, during policy execution so it continues to the next task and doesn't crash the whole thing.
=> Catch approach failures while testing

src/approaches/interactive_learning_approach.py, src/settings.py, tests/approaches/test_interactive_approach.py
Changes the `interactive_known_predicates` config setting to be a string, so it can easily be changed from the commandline.
=> Interactive approach: change known predicates setting to string format

src/approaches/base_approach.py, src/envs/base_env.py, src/main.py, src/utils.py, tests/test_utils.py
@ronuchit the change to `update_config` is not super ideal, but the alternatives -- updating all current and future unit tests to explicitly set `seed`, or keep things the way they are now -- seem less good. lmk what you think though.
cc @NishanthJKumar , who originally pointed out the seed(0) grossness.
=> clean up random seeding

src/planning.py, src/structs.py, tests/test_structs.py
During conversation with @NishanthJKumar , we realized this could help a lot in behavior. For the other environments, it seems to help a little too...
Before change main script termination times:
**Cover / oracle**: 0.42699 seconds
**Blocks / oracle**: 7.29992 seconds
**Painting / oracle**: 5.32841 seconds
After change main script termination times:
**Cover / oracle**: 0.28366 seconds
**Blocks / oracle**: 6.93802 seconds 
**Painting / oracle**: 4.42495 seconds
=> check only expected atom classifiers during planning

analysis/analyze_supercloud_experiments.py, src/args.py, src/utils.py, tests/test_utils.py
The interactive learning approach can't use the excluded predicates flag, so I need some other way to distinguish between different experiment runs. This changes the config and save path strings.
The changes to `analysis/analyze_supercloud_experiments.py` mean the new script won't work on previously saved results.
=> Add "experiment id" flag

src/utils.py, tests/test_utils.py
we realized that static_atoms can be more than just the atoms whose predicate is static under the operators. see updated test for an example
=> fix get_static_atoms()

src/envs/__init__.py, src/envs/cover.py, src/ground_truth_nsrts.py, src/settings.py, tests/approaches/test_oracle_approach.py, tests/envs/test_base_env.py, tests/envs/test_cover.py
this PR has a number of updates to the multistep cover environment to facilitate the option learning project:
1. adds `CoverMultistepOptionsFixedTasks`, a variant where the initial state is fixed (and there are only 3 possible goals).
2. adds `cover_multistep_degenerate_oracle_samplers`, a setting that allows us to use oracle samplers that only sample in the middle of blocks/targets.
3. converts the existing "learned_equivalent" oracle samplers and options to relative parameterization, for consistency with how we're going to learn the options.
4. snaps the robot to the block during picking
5. fixes a few tolerance issues for picking and placing
=> multistep cover env updates

src/utils.py, tests/test_utils.py
this check does not make sense for all policies; for example, policies with certain kinds of memory may be able to get out of "stuck" states.
=> remove policy stuck check

src/envs/painting.py, src/ground_truth_nsrts.py, src/settings.py, tests/envs/test_painting.py
This change makes HoldingSide/Top in painting take in an object instead of a robot. The `held` field of an object has been changed into a `grasp` field, where <0.48 means side grasped, 0.48-0.52 means not grasped, >0.52 means top grasped. The `gripper_rot` field of a robot has been removed.
With lmcut, before this change:
```
Test results: defaultdict(<class 'float'>, {'num_solved': 50, 'num_total': 50, 'avg_suc_time': 0.5432149934768676, 'avg_skeletons_optimized': 1.76, 'min_skeletons_optimized': 1.0, 'max_skeletons_optimized': 2.0, 'avg_nodes_expanded': 802.36, 'avg_plan_length': 14.5, 'avg_execution_failures': 0.0, 'learning_time': 0.0})
Main script terminated in 27.19248 seconds
```
With lmcut, after this change:
```
Test results: defaultdict(<class 'float'>, {'num_solved': 50, …
```
=> update HoldingSide/Top arguments for painting and make painting easier

src/settings.py, tests/approaches/test_grammar_search_invention_approach.py
Big change! Here are oracle results (TL;DR, LM-Cut is worse, but hey, it's optimal...)
```
painting:
lmcut:
Test results: defaultdict(<class 'float'>, {'num_solved': 50, 'num_total': 50, 'avg_suc_time': 0.3736675071716309, 'avg_skeletons_optimized': 1.76, 'min_skeletons_optimized': 1.0, 'max_skeletons_optimized': 2.0, 'avg_nodes_expanded': 479.92, 'avg_nodes_created': 0.0, 'avg_plan_length': 14.5, 'avg_execution_failures': 0.0, 'learning_time': 0.0})
Main script terminated in 18.71742 seconds
previous (hadd):
Test results: defaultdict(<class 'float'>, {'num_solved': 50, 'num_total': 50, 'avg_suc_time': 0.053870744705200195, 'avg_skeletons_optimized': 1.76, 'min_skeletons_optimized': 1.0, 'max_skeletons_optimized': 2.0, 'avg_nodes_expanded': 68.18, 'avg_nodes_created': 0.0, …
```
=> switch to LM-Cut across the board

tests/approaches/test_grammar_search_invention_approach.py, tests/approaches/test_nsrt_learning_approach.py, tests/approaches/test_random_actions_approach.py, tests/approaches/test_random_options_approach.py, tests/test_main.py, tests/test_nsrt_learning.py, tests/test_sampler_learning.py
Remove some tests which have outlived their usefulness, and generally
decrease hyperparameters for some of the slowest tests.
Before this PR, unit tests took about 200 seconds locally. After this
PR, unit tests take about 60 seconds locally.
PS: when invoking pytest, a useful parameter is `--durations=N`, which
will print out the names+times of the `N` slowest tests. `N = 20` is a
reasonable choice.
=> speed up tests ~3.3x

analysis/grammar_search_analysis.py, src/approaches/grammar_search_invention_approach.py, src/planning.py, src/settings.py, tests/approaches/test_grammar_search_invention_approach.py
It's a bit hard to test this right now, but I was able to see some improvement from it. Specifically, what I did was run the analysis script on Cover with the following change:
`expected_planning_time += p * num_nodes` -> `expected_planning_time += p`
I made this change because in our current envs, the number of nodes is helping the score function a lot, making suspicious scores unnecessary.
Results without suspicious scoring:
```
Evaluating predicates: frozenset(), with total cost 0
Total score: 534026.0908040795 computed in 0.072 seconds
Evaluating predicates: frozenset({HandEmpty}), with total cost 1.0
Total score: 534026.0906951863 computed in 0.114 seconds
Evaluating predicates: frozenset({Holding}), with total cost 1.0
Total score: 13071.029276505998 computed in 0.139 seconds
*** …
```
=> add option for suspicious multistep effects score in expected_nodes score function

analysis/grammar_search_analysis.py, src/approaches/__init__.py, src/approaches/base_approach.py, src/approaches/grammar_search_invention_approach.py, src/approaches/interactive_learning_approach.py, src/approaches/iterative_invention_approach.py, src/approaches/nsrt_learning_approach.py, src/approaches/tamp_approach.py, src/datasets/demo_only.py, src/datasets/demo_replay.py, src/main.py, src/option_model.py, src/settings.py, tests/approaches/test_base_approach.py, tests/approaches/test_interactive_approach.py, tests/approaches/test_nsrt_learning_approach.py, tests/approaches/test_oracle_approach.py, tests/approaches/test_random_actions_approach.py, tests/approaches/test_random_options_approach.py, tests/test_main.py, tests/test_option_model.py, tests/test_planning.py
The only places the simulator is now used are:
* option_model.py, within OracleOptionModel
* demo_only.py, for making demos
* demo_replay.py, for making replays
* demo_replay.py, for optionally filtering out optimal replays
* main.py, for evaluation
* interactive_learning_approach.py, a temporary hack to generate
rollouts, which will be fixed in a future PR
=> don't give approaches the simulator

src/approaches/grammar_search_invention_approach.py, src/approaches/interactive_learning_approach.py, src/approaches/iterative_invention_approach.py, src/approaches/nsrt_learning_approach.py
The whole self._dataset thing was put in by me to handle the train_tasks_generator stuff. It's not useful anymore since now, learn_from_offline_dataset is called exactly once. This should have been done as part of #366, but I didn't think of it then.
=> purge self._dataset

src/settings.py, src/teacher.py, tests/test_online_learning.py, tests/test_teacher.py
also change to GroundAtoms themselves instead of (str, objects) for consistency with data+ground_atoms.
=> change ground atoms query and response to allow multiple atoms 

src/main.py
our current code doesn't evaluate learning-based approaches if `num_online_learning_cycles` is 0. also, it doesn't evaluate approaches after the final learning cycle. this should fix both issues
=> main pipeline evaluation schedule fix

src/main.py
before, we would raise a KeyError if PYTHONHASHSEED isn't set at all, which isn't as helpful as the assert message.
=> display better error message when PYTHONHASHSEED is not set

src/approaches/interactive_learning_approach.py, tests/approaches/test_interactive_approach.py
this is a functional change to the interactive approach, and should not be merged until we confirm that we didn't break anything (else) during refactoring.
the functional changes are in active learning:
(1) previously, we would ignore any "negative" responses from the teacher, rather than treating them as known negatives. this actually didn't make a difference though because...
(2) previously, all of the ground atoms that we did not ask about would be treated as negative examples (because they're unlabelled). that's bad, especially because we generally ask about one or a few ground atoms out of many possible, so there would be a whole lot of false negative ground atoms collected during active learning, and active learning could ultimately be harmful. so this change is somewhat of a bug …
=> switch interactive dataset to positive/unlabeled/negative 

src/utils.py, tests/approaches/test_base_approach.py, tests/approaches/test_grammar_search_invention_approach.py, tests/approaches/test_interactive_approach.py, tests/approaches/test_nsrt_learning_approach.py, tests/approaches/test_oracle_approach.py, tests/approaches/test_random_actions_approach.py, tests/approaches/test_random_options_approach.py, tests/datasets/test_datasets.py, tests/envs/test_base_env.py, tests/envs/test_blocks.py, tests/envs/test_cluttered_table.py, tests/envs/test_cover.py, tests/envs/test_painting.py, tests/envs/test_playroom.py, tests/envs/test_repeated_nextto.py, tests/test_main.py, tests/test_models.py, tests/test_nsrt_learning.py, tests/test_online_learning.py, tests/test_option_learning.py, tests/test_option_model.py, tests/test_planning.py, tests/test_sampler_learning.py, tests/test_teacher.py, tests/test_utils.py
this will hopefully put an end to the nightmare of unit tests interfering with each other. we should now use `reset_config` instead of `update_config` in all tests.
I went through all of the tests that previously used `update_config` and removed superfluous things like `seed: 123` (which happens automatically), multiple consecutive calls to `update_config` to deal with the `get_arg_specific_settings` stuff, and calls to `update_config` at the end of unit tests.
=> reset_config instead of update_config in tests

src/approaches/interactive_learning_approach.py, src/settings.py, src/utils.py, tests/approaches/test_interactive_approach.py, tests/test_utils.py
A number of refactors to the active learning part of interactive learning, in preparation for implementing new choices of different subparts.
* `CFG.interactive_action_strategy` controls how we want to set up the exploration policy and termination function
* `CFG.interactive_query_policy` controls how we want to decide what atoms to query in each state
* `CFG.interactive_score_function` controls the score function used in the query policy to determine what atoms are worth querying about
Each of these only has one default choice right now, but I expect we'll implement more options for each in the not too distant future.
Two other minor refactors:
* Combined the two previously separate score functions into one (`_score_atom_set`)
* Refactored `glib_sample` into a generic `sample_subsets` …
=> more refactoring of interactive approach

src/settings.py
things I tested:
* `python src/main.py --env painting --approach nsrt_learning --seed 0`
* `python src/main.py --env painting --approach nsrt_learning --seed 0 --offline_data_method demo`
* `python src/main.py --env cover --approach grammar_search_invention --seed 0 --offline_data_method demo`
* `python src/main.py --env cover --approach grammar_search_invention --seed 0 --offline_data_method demo --excluded_predicates all`
* `python src/main.py --env painting --approach grammar_search_invention --seed 0 --offline_data_method demo --excluded_predicates all --grammar_search_use_handcoded_debug_grammar True --grammar_search_expected_nodes_allow_noops True`
=> change min data for nsrt and painting num train objs 

src/datasets/ground_atom_data.py, tests/approaches/test_interactive_approach.py
Assert that all the predicates we want to learn about (aka the annotating predicates) are all "seen" (commented on by the teacher) in the demo+ground_atoms dataset, in preparation for almost-active-learning-only experiments where only a few training tasks are annotated but we make sure that the robot knows about all the predicates
=> add assertion + test

src/envs/cover.py, src/ground_truth_nsrts.py, tests/envs/test_cover.py
closes #417 
I found two separate issues:
1. we were unwittingly checking collisions between a held block and itself when placing on table. that means that the sampler had to find a free space that was far enough away from the held block's original location, which was sometimes hard, leading to sampler-related failures in planning. I fixed the collision check, and also made the oracle placeontable sampler trivial so it just drops off the object whereever it starts out. (this always works by construction.)
2. in some of the harder problems requiring a plan of length 5 (place, pick, place, pick, place), the skeleton search was getting distracted by skeletons like: place the first object onto the second object's target, then place the second object onto that same target. in these cases, …
=> fixes to cover_regrasp

src/envs/cluttered_table.py
Basically ignore the can we're placing when checking for collisions.
=> fix bug where placing can could collide with its past position

analysis/analyze_results_directory.py
* move AVG_NUM_PREDS more to the right since we look at it often
* remove NUM_TOTAL because it's useless
* if experiment_id column is non-empty, remove env, approach, and
excluded_predicates; so that we're just grouping on experiment_id alone
=> minor improvements to results analysis script

src/nsrt_learning.py
when we print in sorted order, we ruin the order of the printed NSRTs.
this makes them different from the STRIPS operator printouts, which are
in the proper order since we don't sort those. note nsrts is a list, not
a set.
=> improve NSRTs printout

src/datasets/demo_only.py, src/settings.py, tests/datasets/test_datasets.py
for online learning methods, it makes sense to have the number of initial demos and the number of train tasks be two different things, because the method can collect its own data in train tasks that it didn't receive a demo for.
=> max initial demos

src/main.py, src/structs.py, src/teacher.py, tests/approaches/test_interactive_approach.py, tests/test_teacher.py
demonstration responses should be marked as demos. we also will need to know at least the goal that the trajectories are for. one thing to be aware of in general is: now, if a LowLevelTrajectory has train_task_idx 5, it does _not_ mean that the trajectory is a full demonstration of the entire train_task_idx 5; it just means that the trajectory ends up in the goal for that train task, starting at a potentially arbitrary state. if this is too confusing, we may need to make `is_demo`, `train_task_idx`, and `goal` three different properties for `LowLevelTrajectory`. @ronuchit lmk what you think -- I am neutral about whether we should do that.
=> mark demo responses as demos with train task idxs

src/envs/cluttered_table.py, src/ground_truth_nsrts.py, src/settings.py, tests/approaches/test_oracle_approach.py, tests/envs/test_cluttered_table.py
Further constraining cluttered place environment to make task more difficult + goal-conditioned action sampling that works. 
python src/main.py --env cluttered_table_place --approach oracle --max_skeletons_optimized 2 --max_samples_per_step 1 --num_test_tasks 50 --cluttered_table_num_cans_test 2 --cluttered_table_place_goal_conditioned_sampling False  --seed 0
solves 9/50  tasks compared to 
python src/main.py --env cluttered_table_place --approach oracle --max_skeletons_optimized 2 --max_samples_per_step 1 --num_test_tasks 50 --cluttered_table_num_cans_test 2 --cluttered_table_place_goal_conditioned_sampling True  --seed 0 
solves 50/50 tasks
=> Constrained cluttered place

src/approaches/nsrt_learning_approach.py, src/nsrt_learning.py, src/structs.py, tests/test_nsrt_learning.py, tests/test_structs.py
theoretically, a person in the future may want to work on side predicate
stuff. if such a person were to exist, they may appreciate the API
providing the things they would need. this is an attempt to remedy that.
* learn_pnad_side_predicates now takes in PNADs, ground atom data,
train_tasks, predicates, and segments
* added a helper function `op.effect_to_side_predicate()` with tests
=> improve API for side predicate learning

analysis/analyze_results_directory.py, analysis/run_active_learning_baseline.sh, src/approaches/interactive_learning_approach.py, src/main.py, src/structs.py, tests/approaches/test_interactive_approach.py, tests/test_structs.py
it's a little weird because we decided to allow the robot to ask about multiple ground atoms in one state, so in the case of `GroundAtomsHoldQuery` I'm taking "number of queries" to mean "number of ground atoms asked about."
also added some printouts for during the exploration part of online learning
=> Metric for counting num queries made

analysis/run_supercloud_experiments.sh, src/nsrt_learning/sampler_learning.py, src/settings.py, tests/nsrt_learning/test_sampler_learning.py
Edit: opening this PR to turn off sampler classifiers, because they seem unnecessary based on experimentation. Can revert if it's causing problems later down the line.
some of the commits in this PR also close #474 (in particular, the experiment with `--sampler_classifier_neg_check_pre True`)
2/16/22 overnight experiments:
140 jobs per supercloud
ronuchit: control
tslvr: filter out neg data that doesn't match preconditions (`--sampler_classifier_neg_check_pre True`)
njk: no sampler classifier at all (`--sampler_disable_classifier True`)
cc @tomsilver @NishanthJKumar
=> disable sampler classifiers

src/envs/cluttered_table.py, src/ground_truth_nsrts.py, tests/approaches/test_oracle_approach.py
Small changes to the cluttered-table-place env to avoid numerical instability on the edge of the environment. 
python src/main.py --env cluttered_table_place --approach nsrt_learning --sesame_max_skeletons_optimized 2 --sesame_max_samples_per_step 1 --num_test_tasks 50 --cluttered_table_num_cans_test 2 --cluttered_table_place_goal_conditioned_sampling True --seed 0 --sampler_learning_use_goals True --sampler_disable_classifier True
solves 50/50 tasks, 
python src/main.py --env cluttered_table_place --approach nsrt_learning --sesame_max_skeletons_optimized 2 --sesame_max_samples_per_step 1 --num_test_tasks 50 --cluttered_table_num_cans_test 2 --cluttered_table_place_goal_conditioned_sampling True --seed 0 --sampler_learning_use_goals False --sampler_disable_classifier True
solves 34/50.
=> Minor fixes to cluttered place

src/envs/cover.py, src/settings.py, tests/envs/test_cover.py, tests/nsrt_learning/test_option_learning.py
Creates initial state by (1) placing targets and blocks in random locations such that each target has enough space on either side to ensure no covering placement will cause a collision (note that this is not necessary to make the task solveable; but we can do this and instead sufficiently tune the difficulty through hand region specification), and (2) choosing hand region intervals on the targets and blocks such that the problem is solveable.
Note that the hand regions could be made attributes of the target and block objects. This was not done just because it would require editing more code all over the codebase, and creating new "hand region objects" didn't seem like an issue. But, can make this change if preferred.  
There are two kinds of difficulties we want to be able to tune: 
1. …
=> Flexible initial state

src/utils.py, tests/test_utils.py
examples:
* `python src/main.py --env cover --approach oracle --seed 0 --cover_target_widths "[0.03, 0.05]"`
* `python src/main.py --env cover --approach oracle --seed 0 --cover_target_widths [0.03,0.05]`
=> allow lists and tuples on the commandline

src/envs/cover.py, tests/approaches/test_nsrt_learning_approach.py, tests/approaches/test_oracle_approach.py, tests/envs/test_cover.py, tests/nsrt_learning/test_option_learning.py
closes #493 and should resolve the unit test failures in #479 
the issue in #493 was an edge case where the hand is placing outside of both the allowed hand region _and_ outside of the target region. before this PR, the code would think that this placement was a "place on table", which is allowed. but that's not always the case, like in this video:
https://user-images.githubusercontent.com/2816502/156375704-ed0135e9-1f9e-467a-9080-e93cc85f74df.mp4
the unit test failures in #479 were related to default hyperparameter settings being challenging for oracle planning. we want to leave the defaults alone because we want the environment to be challenging, but I made them easier in the relevant unit tests.
=> fixes to cover multistep and tests

analysis/grammar_search_analysis.py, analysis/skeleton_score_analysis.py, src/envs/__init__.py, src/ground_truth_nsrts.py, src/main.py, src/nsrt_learning/option_learning.py, src/nsrt_learning/sampler_learning.py, src/option_model.py, src/settings.py, src/teacher.py, tests/approaches/test_nsrt_learning_approach.py, tests/approaches/test_oracle_approach.py, tests/datasets/test_datasets.py, tests/envs/test_base_env.py, tests/nsrt_learning/test_option_learning.py, tests/test_online_learning.py, tests/test_predicate_search_score_functions.py, tests/test_teacher.py
now there are two methods: `create_new_env` and `get_cached_env`
in the main code path, main.py will be the only thing that calls
`create_new_env` (with `do_cache = True`), and everything else just uses
that same single env instance.
one complication is that for unit testing, we don't want to do caching
at all, so that's why we have a new setting "allow_env_caching"
=> change create_env to get_cached_env_instance in ground truth nsrts

analysis/grammar_search_analysis.py, analysis/skeleton_score_analysis.py, src/envs/__init__.py, src/ground_truth_nsrts.py, src/main.py, src/nsrt_learning/option_learning.py, src/nsrt_learning/sampler_learning.py, src/option_model.py, src/teacher.py, tests/approaches/test_nsrt_learning_approach.py, tests/envs/test_base_env.py, tests/nsrt_learning/test_option_learning.py, tests/test_online_learning.py, tests/test_teacher.py
now there are two methods: `create_new_env` and `get_or_create_env`
in the main code path, main.py will be the only thing that calls
`create_new_env` (with `do_cache = True`), and everything else just uses
that same single env instance.
=> second attempt at create env refactor

src/envs/blocks.py, src/envs/cluttered_table.py, src/envs/cover.py, src/envs/painting.py, src/envs/playroom.py, src/envs/repeated_nextto.py, src/envs/tools.py, src/structs.py, tests/envs/test_cover.py
A few of our environments are maintaining objects internally, even though the number of objects can change according to `CFG` settings. This is now an issue because of the change we made to `create_env`. For example, in #512, a new unit test is failing because that test changes the number of objects in cover using `reset_config`, but then oracle approach calls option model, which loads a cached cover environment, which had the wrong number of objects.
=> Purge unintentional env states

analysis/analyze_results_directory.py, launch_slack_bot.py, src/main.py
* I think we don't actually want scheduled nightlies because they might
conflict with other experiments we want to run, and it would be annoying
to set up a system that pauses them (we'd have to remember to do that).
I think this is a fine compromise: a new command `launch <username>`,
which conveniently handles switching to master, pulling, wiping previous
results, and launching.
* Added git commit hash into `results/` files to help us sanity check that
results are on the commit we expect.
=> updates to slack bot

analysis/seed_scanner.sh
the idea is that you can let this run for a while, and then once you find a seed that's failing, you can dig into that one without having to wait around for a later failing test within a single seed.
=> script for finding a seed that fails on the first test task

launch_slack_bot.py
we have no idea why you can't just do `source ~/.bashrc` instead but it doesn't work
=> bot sets PYTHONHASHSEED

.gitignore, launch_slack_bot.py, scripts/submit.py, supercloud.md
closes #568
* `supercloud_logs` is no more, there is only `logs`
* log names are readable now
* supercloud job names are now readable
* `squeue` is no longer recommended, a custom command `sl` is recommended instead (see updated `supercloud.md`)
=> updates to supercloud run script

src/option_model.py, tests/test_option_model.py
this command crashes before this change, but not after:
```python src/main.py --env cover_multistep_options --approach nsrt_learning --seed 0 --option_learner neural --sampler_learner oracle --num_train_tasks 50```
example crash:
```
Traceback (most recent call last):
File "/Users/tom/phd/predicators/src/main.py", line 336, in <module>
main()
File "/Users/tom/phd/predicators/src/main.py", line 108, in main
_run_pipeline(env, approach, stripped_train_tasks, offline_dataset)
File "/Users/tom/phd/predicators/src/main.py", line 131, in _run_pipeline
results = _run_testing(env, approach)
File "/Users/tom/phd/predicators/src/main.py", line 240, in _run_testing
policy = approach.solve(task, timeout=CFG.timeout)
File "/Users/tom/phd/predicators/src/approaches/base_approach.py", line 51, in solve …
```
=> fix oracle option model for learned options

tests/nsrt_learning/test_option_learning.py
this new longrun test takes about 75 seconds to run. longer than ideal, but if we make the hyperparameters any weaker, I'm not sure if we'll see the option learning signs of life that we want to test.
=> add a long integration test for option learning

scripts/analyze_results_directory.py, src/main.py
Note one issue is that all three of these things are cumulative now --
num_transitions, cumulative_query_cost, learning_time. But we're only
naming one of them "cumulative". Should we just make them all consistent
@tomsilver?
=> fix learning time

src/utils.py
example stack trace:
```
Tasks solved: 50 / 50
Average time for successes: 0.16820 seconds
Traceback (most recent call last):
File "/home/gridsan/ronuchit/predicators/src/main.py", line 344, in <module>
main()
File "/home/gridsan/ronuchit/predicators/src/main.py", line 104, in main
_run_pipeline(env, approach, stripped_train_tasks, offline_dataset)
File "/home/gridsan/ronuchit/predicators/src/main.py", line 133, in _run_pipeline
_save_test_results(results, online_learning_cycle=None)
File "/home/gridsan/ronuchit/predicators/src/main.py", line 335, in _save_test_results
"git_commit_hash": utils.get_git_commit_hash()
File "/home/gridsan/ronuchit/predicators/src/utils.py", line 1740, in get_git_commit_hash
out = subprocess.check_output(["git", "rev-parse", "HEAD"])
File …
```
=> fix weird memory error in supercloud

src/approaches/bilevel_planning_approach.py, src/main.py
example: ```python src/main.py --env cover --approach oracle --seed 0 --num_test_tasks 1 --timeout 0.001```
before:
```
Test results: defaultdict(<class 'float'>, {... 'min_skeletons_optimized': 8, 'max_skeletons_optimized': 0.0, ...})
```
after:
```
Test results: defaultdict(<class 'float'>, {... 'min_skeletons_optimized': 0, 'max_skeletons_optimized': 0.0, ...})
```
=> fix edge case for min_skeletons_optimized metric

src/planning.py, tests/test_planning.py
this was arising with planning using operators that were not sidelined,
in repeated_nextto. i noticed that sometimes the planner was far
exceeding the 10-second timeout. this should fix that.
=> fix an edge case with checking timeout in planner

src/structs.py, tests/test_structs.py
@NishanthJKumar @wmcclinton FYI this will break behavior. to repair, we'll need to create a subclass of `State` for behavior that overrides `allclose`. I can do this when the time comes.
=> disallow using state allclose when simulator_state is defined

scripts/skeleton_score_analysis.py, src/approaches/bilevel_planning_approach.py, src/planning.py, src/predicate_search_score_functions.py, tests/test_planning.py
avoids some circular import issues that were arising when running standalone test files
this was surprisingly not as painful as i thought it would be. i tested a couple of things, but we need to rerun our nightly. cc @tomsilver
=> make planner raise its own Exceptions instead of using approaches'

src/envs/painting.py, src/settings.py, tests/envs/test_painting.py
* no functional change to default code path (verified)
* checked that with box only or shelf only goals, nsrt_learning produces
1:1 operators/options that don't have any HoldingSide/HoldingTop
anywhere respectively, *as long as you also set
painting_initial_holding_prob to 0.0*
=> add box only or shelf only setting for painting

src/envs/repeated_nextto.py
@NishanthJKumar: this will change all the seeding, so let's only merge it after you're pretty confident your implementation is working on the current RNT, just to test a harder set of goals.
Supercloud results:
```
NUM_TRAIN_TASKS    NUM_SOLVED AVG_NUM_PREDS AVG_TEST_TIME AVG_NODES_CREATED LEARNING_TIME  NUM_SEEDS
EXPERIMENT_ID
rnt_backchain    50.00 (0.00)  50.00 (0.00)   3.00 (0.00)   0.05 (0.01)      87.35 (3.21)  11.45 (0.88)         50
rnt_oracle        0.00 (0.00)  50.00 (0.00)   3.00 (0.00)   0.01 (0.00)      87.35 (3.21)   0.00 (0.00)         50
```
=> make rnt goals slightly harder

src/args.py, src/main.py, tests/test_online_learning.py
intended usage: when loading saved models from an online learning approach, it is often useful to skip to a later cycle and inspect things there, e.g., the data, the evaluation failures.
closes #654
=> allow skipping until a learning cycle

src/envs/painting.py, src/envs/repeated_nextto_painting.py, src/ground_truth_nsrts.py, tests/approaches/test_oracle_approach.py, tests/envs/test_painting.py, tests/envs/test_repeated_nextto_painting.py
the hope is to get them closer to what we would expect to learn with sidelining / operator learning
things I tested on seeds 0 - 4:
* `python src/main.py --env repeated_nextto_painting --approach oracle`
* `python src/main.py --env painting --approach oracle`
* `python src/main.py --env repeated_nextto_painting --approach oracle --painting_goal_receptacles box`
* `python src/main.py --env repeated_nextto_painting --approach oracle --painting_goal_receptacles shelf`
=> updates to ground truth nsrts for rnt painting

src/approaches/nsrt_learning_approach.py, src/nsrt_learning/nsrt_learning_main.py, src/nsrt_learning/option_learning.py, tests/nsrt_learning/test_nsrt_learning_main.py, tests/nsrt_learning/test_option_learning.py
this fixes a crash where the learned option policies would suggest out of bounds actions
before this change, this crashes:
`python src/main.py --env touch_point --approach nsrt_learning --seed 1 --option_learner neural`
now it doesn't crash
=> fix action space bound crash for option learning

src/option_model.py, tests/test_option_model.py
before this PR, this command would fail when the learned policy returns nans:
`python src/main.py --env cover_multistep_options --approach nsrt_learning --seed 0 --option_learner neural`
=> handle case where option raises error during option model

src/nsrt_learning/option_learning.py, src/settings.py, src/torch_models.py, tests/approaches/test_nsrt_learning_approach.py, tests/nsrt_learning/test_option_learning.py, tests/test_settings.py, tests/test_torch_models.py
Results below on seeds 0-4 with the touch point environment. Results on cover are no good yet, likely due to higher dimensional action space.
```python src/main.py --approach nsrt_learning --env touch_point --option_learner direct_bc```
*Results*: 47, 45, 45, 48, 40
```python src/main.py --approach nsrt_learning --env touch_point --option_learner implicit_bc```
*Results*: 49, 50, 50, 50, 50
=> implicit regressor and implicit behavior cloning for option learning

scripts/supercloud/run_sidelining_experiments.sh, src/nsrt_learning/side_predicate_learning.py
Introduces a change to how we assign transitions to a particular PNAD's datastore under the `add_effects` semantics. This change does not affect results on RNT or RNT_single_option (Supercloud run over 100 seeds presented below), but is necessary for new keep-effect code to work on RNT_painting. Also, this new check just seems more correct.
[results_summary.csv](https://github.com/Learning-and-Intelligent-Systems/predicators/files/8445825/results_summary.csv)
=> Change to how datastore is calculated under add effect semantics

src/envs/pybullet_utils.py
this happened to not matter when we were using fetch, because the joint with ID 0 was not in the kinematic chain for the arm. but for panda, the joint with ID 0 _is_ in the kinematic chain for the arm, and because of this bug, we were excluding a joint from inverse kinematics, which was making end effector position control not work (cc @williamshen-nz ). the correct value is -1 because that is what pybullet uses for the base.
=> fix bug in pybullet kinematic chain computer

src/envs/painting.py
will degrade performance of bad baselines like random options, but
shouldn't change our main stuff
=> remove painting options' initiable functions

scripts/analyze_results_directory.py, scripts/create_bar_plots.py, scripts/create_interactive_predicate_learning_plots.py, scripts/create_latex_tables.py, scripts/create_plots.py, src/main.py
closes #729
also removed commented out / unused code from analysis scripts. to see what columns are available, we can refer to `analyze_results_directory.py`, we don't need them listed in the other files.
I tested the update to the interactive learning plot by running the "silent kid" command over 3 seeds and 1 learning cycle, and then ran the script. the plots from that are below. (the data are not meaningful, this just shows that the script runs and the axes are what we want.)
=> execution failure metric tweak & plotting different error types for interactive learning

src/envs/pybullet_blocks.py, src/envs/pybullet_env.py, src/envs/pybullet_robots.py, src/utils.py, tests/envs/test_pybullet_blocks.py, tests/envs/test_pybullet_robots.py
this is so that the panda can run IK once and motion plan, if it wants to, but the fetch can still run IK at every time step, which appears to be more stable and effective.
=> move two generic option creators into pybullet robot

src/utils.py
this happened to not matter because I was always using kwargs, but since the first two arguments are x then y, and width corresponds to x and height corresponds to y, this new order is more intuitive
=> change order of Rectangle arguments

src/structs.py
if we save data that has no options (dummy options) and then load a dataset, `has_option` incorrectly reports True, because the `DummyOption` instance is different now, because it's a different Python process.
I looked for other similar cases in the code and didn't see any. there are a few other instances of `is DummyOption`, but those look correct, because they could only refer to the dummy option for the current process.
=> fix `has_option` for loading

src/nsrt_learning/strips_learning/base_strips_learner.py, src/settings.py, tests/nsrt_learning/test_nsrt_learning_main.py
when running experiments that vary the number of training data, it's easier to specify this new flag instead of `min_data_for_nsrt`. but I think we should still leave the old flag since it's useful for testing and is currently being used in a number of @amburger66 's scripts.
=> add `min_perc_data_for_nsrt` flag

src/envs/stick_point.py, src/ground_truth_nsrts.py, tests/envs/test_stick_point.py
* rename all `InContact` to `Above`
* remove redundant predicate between robot and stick (redundant with `Grasped`)
=> stick point env predicate changes

src/envs/cover.py, src/settings.py
before this change, if one were to change `cover_multistep_action_limits` from the default infs to small numbers, then oracle fails because the actions returned by the oracle policy would violate the gripper dimension of the action space.
=> fix for cover multistep option action space limits

src/envs/pybullet_robots.py, tests/envs/test_pybullet_robots.py
* avoid confusion with `robot.inverse_kinematics` by renaming the global method `inverse_kinematics()` to `pybullet_inverse_kinematics()`
* clarify that the `target_position` argument is a Pose3D
=> minor type fix + rename inverse_kinematics()

src/nsrt_learning/option_learning.py, tests/nsrt_learning/test_option_learning.py
closes #856 
I'm going to test this on supercloud with stick button. I would expect that the results for the parameterized methods stay the same or improve. if they don't improve, I can think of two possibilities: there's a bug in this PR, or the `_create_absolute_option_param` function is significantly slow, leading to more timeouts.
=> exclude static features from learned option param spaces

src/planning.py, src/settings.py, tests/test_planning.py
findings on repeated_nextto:
- oracle & our backchaining approach work the same whether it's enabled or disabled, no difference in planning time
- cluster_and_intersect sucks whether it's enabled or disabled, because the skeleton search itself is so difficult with so many high-arity operators. so planning times out in skeleton search itself
- one interesting thing i tried: **if you change the oracle operators to not contain side predicates** (just do side_predicates = set() for both Move and Grasp), **then planning works** (albeit slowly; gets ~40/50) **when the expected atoms check is disabled, but fails unilaterally when it's enabled**. this was interesting to me because i always thought that the expected atoms check is strictly beneficial from a success rate perspective (ignoring …
=> add setting to disable expected atoms check

src/envs/cover.py, src/ground_truth_nsrts.py, src/teacher.py, tests/approaches/test_nsrt_learning_approach.py
closes #874 
this should not be a functional change, except in the case where we are learning options with oracle samplers, in which case this should fix the crash mentioned in the issue.
=> fix correspondence between oracle and learned samplers in cover multistep

src/main.py
this change is due to very long filenames occurring in behavior when all options are included. this PR should fix that
=> simplify dataset filename for included options

requirements-dev.txt
Specifies the version of `yapf`, because @wmcclinton's system happened to `pip install` an older version, which caused all sorts of weird formatting changes. We want to avoid this for any new users in the future!
=> minor change in requirements-dev to specify yapf version

src/envs/doors.py
fixes a crash with oracle options. the old action bounds didn't make sense, they were left over from a time where I was thinking about door handle rotations literally...
=> fix to doors action space

scripts/analyze_results_directory.py, scripts/plotting/create_interactive_predicate_learning_plots.py, scripts/plotting/create_num_demos_plots.py, src/main.py, tests/test_main.py
closes #893 
@amburger66 this change is going to break the plotting script for any results that were previously generated. to plot old results, we could modify the script locally as needed. or, we can make this change backward compatible, but i'm worried then that we're going to get confused about what "num transitions" means... let me know what you think
=> separate online and offline transitions in metrics

src/nsrt_learning/strips_learning/clustering_learner.py, src/settings.py, src/utils.py, tests/test_utils.py
we can try running this as is, but at least based on my local testing, i think we'll still have issues for rnt_painting, because the call to recompute_datastores_from_segments is still very expensive, and i don't know how to get around it.
works well on painting and screws, works decently on rnt_single_option (~40/50)
=> add a strong timeout to prediction error hill climbing baseline

src/nsrt_learning/option_learning.py, src/nsrt_learning/strips_learning/base_strips_learner.py
this fixes some crashes that were arising in prediction error for rnt painting, where if two different option variables map to the same object in a segment’s sub dict, then KnownOptionsOptionLearner will crash, bc it has to invert that mapping to figure out what the option variables are from the objects in each segment’s option (furthermore, this inverted mapping has to be consistent across all segments in the datastore)
supercloud results look good for both nightly and sidelining:
```
3cba5be02b36d0084e9ea13e17ea215f0a62c025
NUM_TRAIN_TASKS    NUM_SOLVED AVG_NUM_PREDS AVG_TEST_TIME  AVG_NODES_CREATED       LEARNING_TIME  NUM_SEEDS
EXPERIMENT_ID …
```
=> disallow groundings with repeated objects in `recompute_datastores_from_segments()`

src/nsrt_learning/strips_learning/base_strips_learner.py, src/nsrt_learning/strips_learning/gen_to_spec_learner.py, src/structs.py, tests/nsrt_learning/strips_learning/test_gen_to_spec_learner.py
A better way of resolving the issue described in detail in #932. We realized that it's okay for keep effects to create new variables, as long as you make sure to reuse those mappings in `recompute_datastores_from_segments()`. This PR implements that functionality and adds a new test for it.
* Verified that the test fails the harmlessness check on master, as we'd expect.
* Verified that the test fails if you don't do the `seg_to_keep_effects_sub` stuff, because the datastore will be wrong, which is checked near the end of the test.
Supercloud (no crashes 🎉 ):
```
cc86499968424fe5b0e22c1790842e129ef87095
NUM_TRAIN_TASKS     NUM_SOLVED AVG_NUM_PREDS AVG_TEST_TIME   AVG_NODES_CREATED  LEARNING_TIME  NUM_SEEDS
EXPERIMENT_ID …
```
=> allow keep effects to create new variables

src/datasets/demo_only.py, src/utils.py
i think this is easier and cleaner than the individual task saving idea in #946, and so we should only do that more complicated thing if we really find it necessary in the future.
closes #946
=> skip training tasks where human demonstrator gave a bad input

src/main.py, tests/test_main.py
Want the metrics dictionary to store how many times each kind of exception occurred so that we get a clearer picture about how and why an approach is failing.
=> Add exception counts to metrics

src/args.py, src/datasets/demo_only.py, src/settings.py
note: this will affect a couple of scripts slightly. in particular:
* stick_button experiments in the nightly require `--timeout 300`, and
so any training examples that fail due to the timeout will take 30x
longer to do so
* similar for ALL experiments in `run_option_learning_experiments.sh`
closes #949
=> make `offline_data_planning_timeout` default to `timeout`

scripts/supercloud/run_predicators_sidelining_experiments.sh, src/nsrt_learning/strips_learning/gen_to_spec_learner.py, tests/nsrt_learning/strips_learning/test_gen_to_spec_learner.py
Gets the intermediate harmlessness check to pass for the longrun tests, resolving the known issue with these tests. 
Conceptually, we want to ensure at the end of our backchaining that:
- The segment.necessary_add_effects should be set correctly.
- We should be able to find a best-matching PNAD (unification) for this segment.
- *This segment should be in the particular PNAD’s datastore.*
We weren't previously explicitly checking this last condition (though it is important only rarely), which leads to intermediate harmlessness violations that get fixed at later iterations of the outer loop.
We now explicitly check this condition, and if it's false, we move the segment into the correct datastore to fix the problem. Here's a diagram of the logic:
It's possible we can accomplish the same …
=> [sidelining] Fix known issue with intermediate harmlessness in longrun tests

src/planning.py
=> add a comment to clarify why planning.py doesn't use `utils.run_astar()`

src/envs/behavior.py, src/ground_truth_nsrts.py
Prevents the creation of ground atoms like `reachable-hardback-hardback(book1, book1)`, which were previously making NSRT learning return complicated and hyper-specific operators.
=> [BEHAVIOR] Cuts down the number of 'reachable' predicates to only what's necessary

src/ml_models.py, src/structs.py, src/utils.py, tests/test_main.py, tests/test_utils.py
Example usage:
`python src/main.py --env cover --approach nsrt_learning --seed 0 --sampler_mlp_classifier_max_itr "lambda n: n * 100"`
```
Tasks solved: 50 / 50
Average time for successes: 0.04212 seconds
Test results: defaultdict(<class 'float'>, {'num_solved': 50, 'num_total': 50, 'avg_suc_time': 0.04211793422698975, 'min_skeletons_optimized': 1.0, 'max_skeletons_optimized': 2.0, 'num_solve_timeouts': 0, 'num_solve_failures': 0, 'num_execution_timeouts': 0, 'num_execution_failures': 0, 'avg_num_skeletons_optimized': 1.1, 'avg_num_nodes_expanded': 2.8, 'avg_num_nodes_created': 6.6, 'avg_num_nsrts': 2.0, 'avg_num_preds': 5.0, 'avg_plan_length': 2.46, 'avg_num_failures_discovered': 0.0, 'num_offline_transitions': 123, 'num_online_transitions': 0, 'query_cost': 0.0, 'learning_time': …
```
=> allow max training iterations in `ml_models.py` to depend on the dataset size

src/approaches/interactive_learning_approach.py, src/ml_models.py, src/settings.py, tests/approaches/test_interactive_approach.py, tests/test_ml_models.py
and add a setting for choosing the predicate classifier model
closes #685 (well, you would still need to actually test with supercloud, but we don't need to keep the issue open for that)
=> slightly refactor `ml_models.py` to allow other ensemble types

scripts/supercloud/run_nightly_experiments.sh, src/envs/coffee.py, src/ground_truth_nsrts.py, tests/envs/test_coffee.py
this is a possible fix to a subtle regression in coffee option learning that was introduced by the change to `apply_operator()` in #984 .
after that change, the number of possible skeletons that appear to solve the task significantly increased, which led to slower overall planning time. by adding this predicate, the hope is to reduce the number of skeletons back to the original and restore option learning results.
also closes #1029 
coffee results:
```
471a97d1f80d09d0d9c5f3aee89fe1fce0f2effc
NUM_TRAIN_TASKS    NUM_SOLVED AVG_NUM_PREDS  AVG_TEST_TIME AVG_NODES_CREATED    LEARNING_TIME  NUM_SEEDS
EXPERIMENT_ID …
```
=> update nightly with option learning expts; add NotSameCup predicate to coffee env

mypy.ini
this is a temporary measure until we have time to do the better thing...
- the scripts subdirectory uses `pandas` in a number of places
- the type annotations are not entirely correct, and it's nontrivial to fix them
- we've been getting away with this because the pandas library is mostly untyped
- but there's another library called `pandas-stubs` that adds type annotations for pandas
- the `openai` package has `pandas-stubs` as a dependency
- so in the short term, to add the `openai` package, we'll just stop type checking the entire scripts directory
- in the longer term, we need to close this issue https://github.com/Learning-and-Intelligent-Systems/predicators/issues/973
=> exclude scripts from type checking

src/approaches/nsrt_learning_approach.py, src/args.py, src/datasets/demo_only.py, src/nsrt_learning/nsrt_learning_main.py, src/utils.py, tests/approaches/test_nsrt_learning_approach.py, tests/nsrt_learning/test_nsrt_learning_main.py, tests/test_utils.py
This PR allows us to save and load GroundAtomTrajectories with the `--load_atoms` flag. This functionality is extremely useful for BEHAVIOR, where running all the classifiers is slow even if we load trajectory data.
=> Saving+Loading GroundAtomTrajectories

src/ground_truth_nsrts.py, src/nsrt_learning/nsrt_learning_main.py, src/nsrt_learning/sampler_learning.py, src/nsrt_learning/strips_learning/oracle_learner.py, tests/approaches/test_nsrt_learning_approach.py, tests/approaches/test_oracle_approach.py, tests/nsrt_learning/strips_learning/test_oracle_learner.py
before this PR, this command would crash:
```
python src/main.py --approach nsrt_learning --seed 0 --env painting --strips_learner oracle --sampler_learner oracle --num_train_tasks 10 --painting_lid_open_prob 1.0 --painting_goal_receptacles shelf
```
and in general, if we are doing oracle strips and sampler learning, and we add settings that lead to some NSRTs having no data, we will now raise a warning instead of crashing.
this is meant to be a more general solution to the problem that I papered over in PRs #1057 and #1065 , so those changes are reverted.
=> handle cases where oracle learner sees no data for nsrts

src/utils.py, tests/approaches/test_online_pg3_approach.py
from speed profiling, I saw that `all_ground_ldl_rules` can be a bottleneck for pg3/4 learning. adding this caching seems to shave off some time.
=> minor optimization for pg3

src/approaches/open_loop_llm_approach.py
this is the crash that I'm trying to fix:
```
Traceback (most recent call last):
File "src/main.py", line 399, in <module>
main()
File "src/main.py", line 114, in main
_run_pipeline(env, approach, stripped_train_tasks, offline_dataset)
File "src/main.py", line 145, in _run_pipeline
results = _run_testing(env, approach)
File "src/main.py", line 304, in _run_testing
traj, execution_metrics = utils.run_policy(
File "/home/ubuntu/predicators/src/utils.py", line 942, in run_policy
raise e
File "/home/ubuntu/predicators/src/utils.py", line 923, in run_policy
act = policy(state)
File "/home/ubuntu/predicators/src/approaches/base_approach.py", line 64, in _policy
act = pi(state)
File "/home/ubuntu/predicators/src/approaches/nsrt_metacontroller_approach.py", line 41, in _policy
ground_nsrt = …
```
=> fix rare crash in open loop llm approach

src/planning.py, tests/test_planning.py
maybe we should run a nightly after this? @tomsilver
=> purge `initial_predicates` from planning.py

predicators/planning.py, predicators/structs.py, tests/test_planning.py, tests/test_structs.py
Previously, FD had no knowledge of operators' ignore effects. As a result, it wasn't able to solve even simple domains (such as `repeated_nextto_single_option`) where ignore effects are necessary.
This PR modifies the PDDL file creation code to parse ignore effects into universally-quantified delete effects that FD can operate on.
You can try this out locally by running the following command before and after this PR:
```
python predicators/main.py --env repeated_nextto_single_option --approach oracle --num_test_tasks 50 --seed 0 --sesame_task_planner fdopt
```
Before this PR, the above would result in slow execution and a large number of failed tasks. Afterwards, FD should be able to solve all 50 tasks.
=> Enables FD to use ignore effects

run_autoformat.sh, scripts/plotting/create_bar_plots.py, scripts/plotting/create_interactive_predicate_learning_plots.py, scripts/plotting/create_latex_tables.py, scripts/plotting/create_num_demos_plots.py, scripts/plotting/create_option_learning_plots.py, setup.py
* pandas-stubs upgraded leading to mypy failures, changed the code to silence those
* pylint upgraded and broke in a very specific case. opened an issue here https://github.com/PyCQA/pylint/issues/7427
* we weren't previously autoformatting setup.py with `run_autoformat.sh`, fixed that too
=> fixing github checks

predicators/args.py, predicators/main.py, tests/test_main.py
usage example:
```python predicators/main.py --env cover --approach oracle --seed 0 --log_file ~/Desktop/logs_testing/test2.log```
I also verified that when the script crashes, the exception is logged.
=> add optional log file flag

scripts/analyze_results_directory.py
this was leading to a tricky bug where
```
python scripts/plotting/create_classification_plots.py --env cover --approach interactive_learning --seed 123 --excluded_predicates Covers,Holding --experiment_id cover-main --num_online_learning_cycles 100 --load_approach --load_data
```
was leading to
```
usage: create_classification_plots.py [-h] [--sidelining]
create_classification_plots.py: error: unrecognized arguments: --env cover --approach interactive_learning --seed 123 --excluded_predicates Covers,Holding --experiment_id cover-main --num_online_learning_cycles 100 --load_approach --load_data
```
and it was because the argparse was getting created when the analysis script was getting imported, rather than inside of create_classification_plots.py itself.
@amburger66 (who found the bug) …
=> move argparse in analyze script

scripts/supercloud/submit_supercloud_job.py
When requesting a GPU on supercloud, the partition needs to be `--partition=xeon-g6-volta` and not `--partition=xeon-p8`. Also, the `--gres` argument cannot appear at the end of the string, but rather must appear before the `sh` filename.
Tested and verified this works on launching a BEHAVIOR experiment (in `predicators_behavior` repo).
=> fix supercloud GPU command string

predicators/envs/pybullet_env.py
closes #1181
at some point, pybullet changed the output of `getCameraImage` to be a flat vector instead of the RGBA image.
=> fix pybullet rendering

predicators/envs/blocks.py, predicators/envs/pybullet_blocks.py, tests/envs/test_pybullet_blocks.py
as we move toward real world block stacking, we want to be able to consume a task specification that includes block colors (see #1218). the "right" way to handle this in our framework is to make color part of the block state. this PR investigates whether that will break things. in particular, we'll have to see whether any part of the learning pipeline overfits to color (predicate invention especially). if there is obvious performance degradation, we can hack around it by saving the correspondence between object and colors in the environment itself, but that is pretty ugly because objects vary per task.
=> make rgb color part of block state

predicators/envs/repeated_nextto.py, predicators/ground_truth_nsrts.py, tests/approaches/test_oracle_approach.py
Includes a new variant of the repeated nextto env that causes our backchaining algorithm to learn unnecessarily complex NSRTs. In this `repeated_nextto_ambiguous` environment, backchaining learns the following NSRTs:
```
STRIPS-Grasp0:
Parameters: [?x0:robot, ?x1:dot]
Preconditions: [NextTo(?x0:robot, ?x1:dot)]
Add Effects: [Grasped(?x0:robot, ?x1:dot)]
Delete Effects: [NextTo(?x0:robot, ?x1:dot)]
Ignore Effects: []
Option Spec: Grasp(?x0:robot, ?x1:dot)
STRIPS-Move0:
Parameters: [?x0:robot, ?x1:dot]
Preconditions: [NextTo(?x0:robot, ?x1:dot)]
Add Effects: []
Delete Effects: []
Ignore Effects: []
Option Spec: Move(?x0:robot, ?x1:dot)
STRIPS-Move1:
Parameters: [?x0:robot, ?x1:dot, ?x2:dot, ?x3:dot]
Preconditions: [NextToNothing(?x0:robot)]
Add Effects: [NextTo(?x0:robot, ?x1:dot), …
```
=> RNT environment with ambiguous demos

predicators/envs/pybullet_blocks.py, predicators/envs/pybullet_cover.py, predicators/pybullet_helpers/robots/__init__.py, predicators/settings.py, tests/pybullet_helpers/test_pybullet_robots.py
should fix a bug in the kinematic action space converter where a bad default (0.0, 0.0, 0.0, 0.1) end effector rotation was getting used during IK (and the wrist was facing upward). also tries to head off similar issues in the future by making the default end effector rotation a global setting.
=> make pybullet robot ee orns global settings 

predicators/envs/pybullet_env.py, predicators/settings.py
example:
```python predicators/main.py --env pybullet_blocks --approach oracle --seed 0 --use_gui --pybullet_robot panda --make_test_videos --pybullet_camera_width 1674 --pybullet_camera_height 900 --pybullet_control_mode reset --pybullet_max_vel_norm 100000```
https://user-images.githubusercontent.com/2816502/202010135-3432d203-bd34-4f85-b2f2-3498a756e2f4.mp4
the lagging is a separate issue (#1296) that is also on master. the command gets 50/50
note that we shouldn't change the defaults because with "position" control mode, you need a small max_vel_norm, otherwise physics leads to chaos
=> convert max vel norm to setting

predicators/nsrt_learning/strips_learning/base_strips_learner.py, predicators/nsrt_learning/strips_learning/effect_search_learner.py, predicators/nsrt_learning/strips_learning/gen_to_spec_learner.py, predicators/nsrt_learning/strips_learning/pnad_search_learner.py, predicators/structs.py, tests/nsrt_learning/strips_learning/test_backchaining_based_learners.py
This PR introduces a sweeping set of changes to simplify the `EffectSearchSTRIPSLearner`. The primary goal here is to get rid of the `EffectSets` class and just search over PNADs, since we realized this allows us to achieve the same functionality. Some other major changes include:
- The `GeneralToSpecificSTRIPSLearner` class now has a number of methods (e.g. for spawning a new PNAD, creating PNADs with keep effects, etc.) that previously lived in the `BackchainingSTRIPSLearner` class. This is to enable sharing these methods with the `EffectSearchSTRIPSLearner`.
- Consequently, the `EffectSearchSTRIPSLearner` is now a subclass of the `GeneralToSpecificSTRIPSLearner`.
- The heuristic/score function for effects search now has a complexity term (previously, it only had a coverage term). The …
=> Hill-Climbing Effects Search over PNADs

predicators/nsrt_learning/strips_learning/pnad_search_learner.py
Previously, we always just deleted PNADs during hill-climbing to form a new PNAD set without recomputing them. Rather, we'd always recompute when we started to compute our heuristic. But it makes much more sense to recompute after deletion instead.
=> Recomputes PNADs after 'delete' operator during hill-climbing

predicators/envs/blocks.py, predicators/envs/playroom.py, predicators/envs/pybullet_blocks.py, predicators/settings.py, tests/envs/test_blocks.py, tests/envs/test_pybullet_blocks.py
closes #1298 which ultimately boiled down to being unable to distinguish the fetch gripper being "open" from it "closing" around the larger block.
this command now works as before:
```
python predicators/main.py --env pybullet_blocks --approach nsrt_learning --seed 0
```
for real-world experiments with the panda, we will just override the default with `--blocks_block_size 0.0505`
=> revert default block size to fix fetch nsrt learning

predicators/planning.py, predicators/settings.py, tests/test_planning.py
intended for use in pybullet blocks (real robot experiments). this should prevent us from finding plans that have major collisions between the robot and neighboring blocks. 
the `1e-3` tolerance can't be lower because things appear to slightly move around on their own in pybullet.
default to False because some environments (e.g., Cover) don't obey this assumption about skill scope.
=> check for changes in assumedly static objects during planning 

predicators/args.py, predicators/main.py, tests/test_main.py
will be useful for real robot pipeline where we don't want to continue if planning fails
=> `--crash_on_failure` flag 

predicators/approaches/refinement_estimation_approach.py, predicators/planning.py, predicators/refinement_estimators/__init__.py, predicators/refinement_estimators/base_refinement_estimator.py, predicators/refinement_estimators/oracle_refinement_estimator.py, predicators/settings.py, tests/approaches/test_refinement_estimation_approach.py, tests/refinement_estimators/test_base_refinement_estimator.py, tests/refinement_estimators/test_oracle_refinement_estimator.py
**Changes:**
- Created `predicators/refinement_estimators/` which contains an abstract `BaseRefinementEstimator` and implemented `OracleRefinementEstimator` class (oracle implemented for `narrow_passage` env only)
- Added tests for the refinement cost estimators
- Created a new `RefinementEstimationApproach` which passes a refinement estimator to the planner, and tests based on the oracle approach tests
- `sesame_plan()` takes in an optional refinement estimator. If it is provided, during A* search we pre-generate N skeletons, sort them by estimated refinement cost, and attempt to refine them in that order
- New CFG parameters:
- `refinement_estimator` is a choice of refinement estimator (default: `oracle`)
- `refinement_estimation_num_skeletons_generated` is the number of skeletons to …
=> added refinement cost estimator classes and refinement_estimation approach

predicators/nsrt_learning/strips_learning/base_strips_learner.py
This slows us down somewhat substantially when learning takes a while because we're unnecessarily calling learning twice!
@wmcclinton - is it safe to take out this line entirely (seems so to me)? If not, can we at least move it so that it doesn't get called if `CFG.enable_harmless_op_pruning` is False?
=> removes unnecessary call to learning

predicators/nsrt_learning/strips_learning/pnad_search_learner.py, predicators/settings.py, scripts/lisdf_plan_to_reset.py, tests/nsrt_learning/strips_learning/test_backchaining_based_learners.py
Includes a new flag to run the `pnad_search` learner without the deletion operator during hill-climbing.
Example:
```
python predicators/main.py --env repeated_nextto_ambiguous --approach nsrt_learning --seed 0 --strips_learner pnad_search --pnad_search_without_del True
```
PS: idk why but the autoformat script changed `lisdf_plan_to_reset.py`...
=> Pnad search without deletion

predicators/nsrt_learning/strips_learning/pnad_search_learner.py, predicators/structs.py
This PR adds a `copy()` method to the PNAD datatype such that if a PNAD is copied, modifying any aspect of the original PNAD will not affect this new copied PNAD.
Previously, when running the `pnad_search` learner, it was possible to modify a PNADs `seg_to_keep_effects_sub` by calling the `BackchainingHeuristic` on the same PNAD from a different PNAD set. This led to an extremely strange situation where the heuristic value of a particular PNAD set would change. This apparently doesn't affect most of our domains/tests, but causes some nasty bugs on particular BEHAVIOR seeds where we tend to learn complex operators due to local minima. This change fixes that (confirmed by testing on the `predicators_behavior` repo).
```
NUM_TRAIN_TASKS     NUM_SOLVED …
```
=> Fixes heuristic stochasticity issue with PNAD search

predicators/utils.py, scripts/plotting/create_ignore_effects_lineplots.py
I'm not sure why there are inconsistencies in when and where these mypy errors are coming up, but they should hopefully be fixed now. there were two issues:
1. the `_S` variable that we use for heuristic search needs to be hashable, but states don't need to be hashable in BiRRT (e.g., they're often numpy arrays)
2. needed to add an assertion to suppress a mypy error in the ignore effects plotting script that I was getting locally
=> two mypy fixes

predicators/approaches/online_nsrt_learning_approach.py, predicators/explorers/glib_explorer.py, predicators/settings.py, tests/approaches/test_online_nsrt_learning_approach.py, tests/explorers/test_glib_explorer.py
in the original implementation of GLIB, we would only babble goals that had _never_ been seen before. in the predicators implementation, we were babbling goals in order of the _number_ of times that they had been seen, so the same goal could get babbled multiple times. this is actually bad because it's possible to get into situations where you babble the same goals that appear reachable over and over again, and never fall back to taking random actions, while not realizing that some other goals would be reachable if you corrected your faulty operators. I saw this happen sometimes while messing around with PDDL blocks.
this change may impact @amburger66 's baseline results, but the old results can be recovered by changing the new `online_interaction_max_novelty_count` flag to inf.
=> change glib novelty function to match original implementation

.gitignore
When tests are run locally, the `tests/_fake_trajs` folder gets populated with random trajs. This PR adds that folder to the gitignore so that these aren't committed to the repo unnecessarily.
=> Minor GitIgnore update to prevent unnecessary traj data from being committed to GitHub

predicators/approaches/grammar_search_invention_approach.py, predicators/settings.py, predicators/utils.py, tests/approaches/test_grammar_search_invention_approach.py
Changes necessary to get arity-2 classifiers. This is being implemented in anticipation of doing predicate invention in domains that are more complex than original AAAI paper domains.
To run, try:
```
python predicators/main.py --env cover --approach grammar_search_invention --excluded_predicates all --num_train_tasks 20 --seed 456 --grammar_search_grammar_use_diff_features True
```
Interestingly, this solves 46/50 eval tasks, while setting the `--grammar_search_grammar_use_diff_features True` arg to `False` only solves 43.
=> Implements arity-2 classifiers

predicators/envs/base_env.py, predicators/envs/blocks.py, predicators/settings.py, scripts/run_blocks_real.sh, tests/envs/test_blocks.py, tests/envs/test_cover.py, tests/envs/test_pybullet_blocks.py
this was previously implemented for blocks only. new environments will still need to implement `_load_task_from_json` but that's it.
=> generalize loading test tasks from json files

predicators/planning.py, predicators/settings.py, scripts/configs/interactive_learning.yaml, tests/test_planning.py
`CFG.sesame_use_necessary_atoms` defaults to True, but should be set to False for interactive learning experiments as using the necessary atoms sequence was making the GLIB action baseline perform abnormally well
=> Add flag for toggling usage of necessary atoms sequence in `planning.py`

predicators/nsrt_learning/strips_learning/pnad_search_learner.py, predicators/utils.py
Previously, during predicate invention using `pnad_search` as the operator learning method, we would log the hill-climbing of `pnad_search` operator learning **within each iteration of predicate learning**. This made it a nightmare to try to read the terminal to get a sense of the predicate learning progress. This PR introduces a flag that silences the operator-learning printouts when we're calling `pnad_search` as part of predicate invention.
=> Silence pnad_search hill-climbing during predicate invention.

predicators/envs/sandwich.py, predicators/ground_truth_nsrts.py, predicators/settings.py, predicators/structs.py, tests/approaches/test_oracle_approach.py, tests/envs/test_sandwich.py
new environment where a fixed-base robot makes sandwiches.
* the main motivation for this environment is to work towards a real robot demo with the panda (cc @williamshen-nz ).
* the objects are inspired by [this sandwich making play set](https://a.co/d/gM2CzjS), which I'm hoping we can buy and use with the panda
* the environment may also be useful for active predicate learning (@amburger66 )
here are some renderings:
* https://user-images.githubusercontent.com/2816502/216854567-dcb3f030-c635-441d-9227-c029ec51d876.mp4
* https://user-images.githubusercontent.com/2816502/216854572-307aae9a-58a1-4b6d-aa3b-aabeb718bc73.mp4
* https://user-images.githubusercontent.com/2816502/216854578-ebf1a4ad-3113-4a7d-80d8-fdd98687acac.mp4
notes about the renderings:
* the left is a side view and the right …
=> sandwich environment

predicators/envs/touch_point.py, predicators/ground_truth_nsrts.py, tests/approaches/test_oracle_approach.py, tests/envs/test_touch_point.py
Adds a toy environment involving two options for testing the nsrt RL approach, one for moving to a door (just like moving to a point in TouchPointEnv), and another for opening a door (just like opening a door in DoorsEnv).
=> Add TouchOpenEnv toy domain for testing nsrt rl approach.

predicators/envs/sandwich.py, predicators/ground_truth_nsrts.py, tests/envs/test_sandwich.py
Gives each ingredient obj and the board a "clear" feature so that all predicates can be learned with the assumption that they are a function of only their argument's states
=> `SandwichEnvClear`

predicators/envs/narrow_passage.py, predicators/refinement_estimators/oracle_refinement_estimator.py, predicators/settings.py, tests/approaches/test_oracle_approach.py, tests/approaches/test_refinement_estimation_approach.py, tests/envs/test_narrow_passage.py, tests/refinement_estimators/test_oracle_refinement_estimator.py, tests/test_train_refinement_estimator.py
**Summary of changes:**
- `narrow_passage` environment randomly initializes the widths of the door and narrow passage for each task, as opposed to using a fixed width based on CFG parameters
- `narrow_passage` environment can no longer maintain a static geom cache
- CFG settings changed to take lower bounds and upper bounds for the door and passage width paddings
=> [narrow_passage] Randomly vary narrow_passage door/passage widths between task initializations

predicators/ml_models.py, tests/test_ml_models.py
**Summary of Changes:**
- Added a `CNNRegressor` class modeled off of `MLPRegressor`, which is a regression model composed of CNN-ReLU-MaxPool blocks, a flatten layer, and then linear-ReLU layers.
- Added tests for `CNNRegressor`
- Refactored `ml_models.py` so that all instances of `self._x_dim` are now tuples instead of single integers, to make it more flexible for inputs with more than 2 dimensions. Added some assertions in other model definitions that X is 2D in cases where it seemed necessary.
=> [ml_models] Added a CNNRegressor

predicators/envs/pybullet_cover.py, tests/envs/test_pybullet_cover.py
closes #1400
I wanted to add a more direct test of the oracle approach, but it's not completely straightforward because our oracle approach tests currently use `env.simulate`, which is not implemented for pybullet cover. we could change that, but that's a much bigger change than I have the stomach for at the moment
=> fix pybullet cover

predicators/envs/base_env.py, predicators/main.py, predicators/settings.py, predicators/utils.py, tests/approaches/test_online_nsrt_learning_approach.py, tests/test_utils.py
This PR adds an online_learning_use_last_state, to load the last_state during online exploration instead of sampling a random state. Try with command:
```python predicators/main.py --approach online_nsrt_learning --seed 0  --env cover --explorer glib --max_initial_demos 1 --num_train_tasks 1 --num_test_tasks 10 --max_num_steps_interaction_request 10000 --min_data_for_nsrt 10 --num_online_learning_cycles 1 --online_learning_lifelong True```
=> Added online_learning_lifelong Flag

predicators/approaches/bilevel_planning_approach.py, predicators/settings.py, tests/approaches/test_oracle_approach.py
with `--bilevel_plan_without_sim True`, it will now be possible to run bilevel planning-based approaches but with only task planning run, to avoid the need for a `simulate()` function in the environment.
this flag will only work in environments that are not "TAMP-interesting" in that the first skeleton is assumed to work and all samples are assumed to work.
it's useful for getting simpler environments off the ground (e.g., forthcoming sokoban environment, cozmo environment.)
closes #1420
=> add `bilevel_plan_without_sim` setting

predicators/approaches/bilevel_planning_approach.py, predicators/planning.py, tests/approaches/test_oracle_approach.py, tests/test_planning.py
Enables use of FD with the `--bilevel_plan_without_sim` flag set to `True`. Will be useful for environments like sokoban (#1426 ) that are challenging for task planning.
Example command:
```
python predicators/main.py --seed 0 --env pddl_blocks_procedural_tasks --approach oracle --num_train_tasks 0 --num_test_tasks 5 --bilevel_plan_without_sim True --sesame_task_planner fdopt
```
=> implements FD task planning

predicators/envs/sokoban.py, tests/envs/test_sokoban.py
before this, we would be seeding the gym environment with 0, 1, 2, 3... in the first experiment, and then 1, 2, 3, 4... in the second experiment, etc., because we usually just increment seeds when we run multiple trials.
closes #1432
=> make sokoban seeds independent

predicators/approaches/bilevel_planning_approach.py, predicators/approaches/bridge_policy_approach.py, predicators/bridge_policies/__init__.py, predicators/bridge_policies/base_bridge_policy.py, predicators/bridge_policies/oracle_bridge_policy.py, predicators/envs/painting.py, predicators/settings.py, predicators/structs.py, tests/approaches/test_bridge_policy_approach.py, tests/bridge_policies/test_base_bridge_policy.py, tests/bridge_policies/test_oracle_bridge_policy.py
solving painting without a simulator! also, as a bonus, solving much larger painting problems than ever before possible (see below).
example:
```python predicators/main.py --env painting --approach bridge_policy --seed 0 --painting_lid_open_prob 0.0 --painting_raise_environment_failure False --debug```
leads to
```
Using NSRT PickFromSide(obj0:obj, robby:robot) from planner.
Using NSRT Wash(obj0:obj, robby:robot) from planner.
Using NSRT Dry(obj0:obj, robby:robot) from planner.
Using NSRT PaintToShelf(obj0:obj, receptacle_shelf:shelf, robby:robot) from planner.
Using NSRT PlaceInShelf(obj0:obj, receptacle_shelf:shelf, robby:robot) from planner.
Using NSRT PickFromTop(obj2:obj, robby:robot) from planner.
Using NSRT PaintToBox(obj2:obj, receptacle_box:box, robby:robot) from planner.
Using …
```
=> oracle bridge policy approach

predicators/envs/cluttered_table.py
small fix to a silly bug, not sure how we never saw this before (I guess we haven't used this env much)
=> disable collision checking with trashed cans in cluttered table

predicators/envs/exit_garage.py, predicators/ground_truth_models/exit_garage/__init__.py, predicators/ground_truth_models/exit_garage/options.py, predicators/settings.py, tests/envs/test_exit_garage.py
because I want to use the environment for some bridge policy stuff. these changes should have no effect on the existing code unless you pass in new flags.
there are two new flags:
1. if `--exit_garage_raise_environment_failure True`, then an `EnvironmentFailure` is raised when the car collides with an object.
2. if `--exit_garage_motion_planning_ignore_obstacles True`, then the motion planner does not take into account the obstacles at all.
together, the idea is that we'll make an optimistic plan that ignores the obstacles and then use a bridge policy to store the obstacles when an EnvironmentFailure is encountered.
=> a few new flags for exit garage environment

.predicators_pylintrc, mypy.ini, predicators/envs/cover.py, predicators/ground_truth_models/cover/nsrts.py, predicators/ground_truth_models/cover/options.py, predicators/settings.py, tests/approaches/test_oracle_approach.py
a variation on the cover environment where some blocks are "bumpy", making them harder to grasp. concretely, bumps are implemented as fine-grained and sparse allowed hand regions. see the video below. this environment is intended for developing sampler learning approaches.
example:
```
python predicators/main.py --approach oracle --env bumpy_cover --seed 0 --num_test_tasks 3 --make_test_videos
```
https://github.com/Learning-and-Intelligent-Systems/predicators/assets/2816502/78e54a5f-38c5-4645-a086-42aa5fbcfc58
=> bumpy cover environment

predicators/main.py, predicators/settings.py
the flag is broken because the environment is never reset during training (not even once at the beginning). it's also not possible to periodically evaluate the agent if we use just one long training interaction.
=> remove broken lifelong learning flag

predicators/ground_truth_models/cover/__init__.py, predicators/ground_truth_models/cover/nsrts.py, predicators/ground_truth_models/cover/options.py
in the sampler learning work, it is convenient implementation-wise to assume a 1:1 relationship between options and operators. we don't need this assumption conceptually; it is just a convenience.
=> make options and operators 1:1 in bumpy cover env

predicators/approaches/bilevel_planning_approach.py, predicators/approaches/oracle_approach.py, predicators/datasets/demo_only.py, predicators/settings.py, tests/datasets/test_datasets.py
in environments where we do have a simulator implemented, we may still want to use bilevel planning to collect demonstrations for convenience, even if we otherwise will assume that no simulator exists during training and evaluation.
=> bilevel plan no sim: differentiate offline data collection from main

predicators/envs/cover.py, predicators/ground_truth_models/cover/nsrts.py, predicators/settings.py, tests/approaches/test_oracle_approach.py
the purpose of this flag is to test whether we can learn samplers that are aware of the task distribution. in particular, the pick grasp sampler should favor picking on the right side of blocks if it is only possible to place on the right side of targets.
=> flag to offset target allowed hand region in bumpy cover

predicators/approaches/active_sampler_learning_approach.py, predicators/settings.py, tests/approaches/test_active_sampler_learning_approach.py
Previously, we were creating datasets for active sampler learning for bumpy cover such that a sample is deemed 'successful' if the corresponding ground NSRT's effects are achieved. This works as long as `bumpy_cover_right_targets` is False. We now amend the sampler dataset creation to handle this.
Command:
```
python predicators/main.py --approach active_sampler_learning         --env bumpy_cover         --seed 0         --strips_learner oracle         --sampler_learner oracle         --sampler_disable_classifier True         --bilevel_plan_without_sim True         --offline_data_bilevel_plan_without_sim False         --explorer random_nsrts         --max_initial_demos 1         --num_train_tasks 1000         --num_test_tasks 100         --max_num_steps_interaction_request 15 …
```
=> Gets `ActiveSamplerLearningApproach` working for right_targets

predicators/approaches/active_sampler_learning_approach.py, predicators/nsrt_learning/nsrt_learning_main.py, predicators/nsrt_learning/strips_learning/oracle_learner.py, predicators/settings.py, tests/approaches/test_active_sampler_learning_approach.py, tests/approaches/test_nsrt_learning_approach.py
overdue!
this command leads to 97/100
```
python predicators/main.py --approach active_sampler_learning         --env bumpy_cover         --seed 0         --strips_learner oracle         --sampler_learner oracle         --sampler_disable_classifier True         --bilevel_plan_without_sim True         --offline_data_bilevel_plan_without_sim False         --explorer random_nsrts         --max_initial_demos 0         --num_train_tasks 1000         --num_test_tasks 100         --max_num_steps_interaction_request 15    --bumpy_cover_num_bumps 2         --bumpy_cover_spaces_per_bump 1         --sampler_mlp_classifier_max_itr 1000000         --pytorch_train_print_every 10000 --online_nsrt_learning_requests_per_cycle 10
``
=> make it possible to run active sampler learning without any demonstrations

predicators/approaches/active_sampler_learning_approach.py, predicators/explorers/__init__.py, predicators/explorers/active_sampler_explorer.py, predicators/settings.py, scripts/configs/active_sampler_learning.yaml, scripts/plotting/create_active_sampler_learning_plots.py, tests/approaches/test_active_sampler_learning_approach.py, tests/explorers/test_active_sampler_explorer.py
Includes new ensemble learner approach for active learning. Example command:
```
python predicators/main.py --env bumpy_cover --approach active_sampler_learning --strips_learner oracle --sampler_learner oracle --bilevel_plan_without_sim True --max_initial_demos 0 --num_train_tasks 1000 --num_test_tasks 100 --max_num_steps_interaction_request 50 --sampler_mlp_classifier_max_itr 100000 --mlp_classifier_balance_data False --pytorch_train_print_every 10000 --explorer random_nsrts --online_nsrt_learning_requests_per_cycle 10 --num_online_learning_cycles 25 --active_sampler_learning_model myopic_classifier_ensemble --active_sampler_learning_use_teacher True --bumpy_cover_right_targets True --seed 123
```
=> Ensemble classifier with entropy-based exploration

predicators/explorers/active_sampler_explorer.py
this is a pretty bad bug that was causing a bunch of nonsensical sampler data to get recorded (in a certain case described below).
the bug was in `self._last_executed_nsrt` and the other fields not getting properly reset to `None` after each interaction request. I mistakenly believed that `_get_exploration_strategy()` was getting called after each of the N interaction requests per online learning cycle, but that's not true -- it's called N times _before_ the online learning cycle. the whole "request" setup that we have is quite confusing and regrettable, but a larger refactor is not worth it right now.
the reason we didn't encounter this bug earlier is that we were almost always doing `--online_nsrt_learning_requests_per_cycle 1`, in which case the bug doesn't manifest.
=> fix bug in active sampler explorer

predicators/explorers/active_sampler_explorer.py, predicators/main.py, predicators/nsrt_learning/segmentation.py, predicators/utils.py, tests/explorers/test_active_sampler_explorer.py
first, the change I made in https://github.com/Learning-and-Intelligent-Systems/predicators/pull/1499 was just completely wrong. it was looking at the time step in the entire trajectory to determine whether the current option has exceeded the max horizon.
second, the ground op history (for sampler learning) inside the active sampler explorer was not recording data in the case where the episode is terminated due to the max option horizon.
before these changes, there were discrepancies between the number of data per operator reported by the active sampler explorer versus the number reported within the approach for sampler learning. the numbers are consistent after these fixes.
=> fix two bugs related to segmentation in active sampler learning

predicators/envs/kitchen.py, predicators/ground_truth_models/kitchen/options.py
a RuntimeError is raised on supercloud when running non-mujoco configs
=> fix mujoco import error on supercloud

mypy.ini, predicators/envs/kitchen.py, predicators/ground_truth_models/kitchen/nsrts.py, predicators/ground_truth_models/kitchen/options.py, predicators/perception/kitchen_perceiver.py, predicators/settings.py, setup.py, tests/envs/test_kitchen.py
this replaces the gym environment ("back end") for the kitchen environment to a more recent and stable version. the main advantage of the new version is that stable IK control of the end effector is possible, which massively reduces pain in designing options.
it's also possible that we could make the kitchen environment a regular dependency, but I'm punting on that because it requires a higher python version (3.9+) than our current minimum (3.8).
this PR recovers the performance of the "perfect" samplers. the next PRs will (1) recover performance of active learning; (2) recover supercloud-ability; (3) add more skills.
=> change kitchen backend

predicators/nsrt_learning/strips_learning/pnad_search_learner.py
`pnad_search` with predicate invention by oracle clustering enters an infinite loop in the blocks environment due to an issue with the backchaining implementation. This happens because `PNADSearchSTRIPSLearner.backchain` only tries the _single_ best matching pnad for a given segment – if that pnad doesn't satisfy the necessary atoms check, it does not check if any other pnads would work. In the specific example where this issue arises, `pnad_search` repeatedly uncovers the same segment over and over: a pnad (`STRIPS-Pick8`) covers a particular segment and has this segment in its datastore, but `PNADSearchSTRIPSLearner.backchain` continues to identify this segment as an uncovered segment. This happens because in the search for the first uncovered segment, when backchaining, it only tries …
=> Fix pnad search backchaining

predicators/ground_truth_models/cover/nsrts.py, predicators/ground_truth_models/cover/options.py, predicators/settings.py, tests/envs/test_cover.py
upcoming changes to the active learning approach should realize that the NSRT is impossible and opt not to use it
command that we can use to test future improvements:
```
python predicators/main.py --env regional_bumpy_cover --approach active_sampler_learning --experiment_id regional_bumpy_cover-main_explore --debug --strips_learner oracle --sampler_learner oracle --bilevel_plan_without_sim True --max_initial_demos 0 --sampler_mlp_classifier_max_itr 100000 --mlp_classifier_balance_data False --pytorch_train_print_every 10000 --active_sampler_learning_model myopic_classifier_mlp --active_sampler_learning_use_teacher False --online_nsrt_learning_requests_per_cycle 5 --num_online_learning_cycles 10 --active_sampler_learning_explore_length_base 10000 --explorer active_sampler …
```
=> add optional impossible NSRT to regional bumpy cover environment

predicators/approaches/maple_q_approach.py, predicators/ml_models.py, predicators/settings.py, scripts/configs/active_sampler_learning.yaml, scripts/configs/online_rl_cover.yaml, scripts/local/launch.py, tests/test_ml_models.py
Continuous Cover MAPLE Q Results with this change:
```
NUM_TRAIN_TASKS    NUM_SOLVED AVG_NUM_PREDS AVG_TEST_TIME AVG_NODES_CREATED   LEARNING_TIME AVG_REF_COST  NUM_SEEDS
EXPERIMENT_ID                           CYCLE                                                                                                                    
continuous_regional_bumpy_cover-maple_q 0      1000.00 (0.00)   2.80 (3.66)   0.00 (0.00)   0.04 (0.00)       0.00 (0.00)   90.18 (27.60)  0.16 (0.04)          5
1      1000.00 (0.00)   6.60 (4.27)   0.00 (0.00)   0.04 (0.00)       0.00 (0.00)  133.27 (36.76)  0.16 (0.10)          5
10     1000.00 (0.00)   6.40 (4.13)   0.00 (0.00)   0.04 (0.00)       0.00 (0.00)  376.11 (53.54)  0.16 (0.10)          5
11     1000.00 (0.00)   7.80 …
```
=> Adding a replay buffer to Maple Q Training

predicators/approaches/bilevel_planning_approach.py, predicators/explorers/active_sampler_explorer.py, predicators/planning.py, tests/test_planning.py
During active sampler learning, instead of measuring success rate under a particular timeout, we might want to measure success rate under a particular horizon. We can do this by setting the `--horizon` argument to whatever particular number we want when running our experiments. However, this causes an issue with approaches that call the planner during exploration: in particular, these will sometimes come up with plans they want to practice that might be longer than the given horizon. If this happens, an error gets thrown that causes a crash...
This PR sets the horizon to `np.inf` during exploration, thereby disabling the horizon check during exploration, but keeping it around for use at evaluation time.
=> Implement infinite-horizon for exploration

predicators/approaches/online_nsrt_learning_approach.py, predicators/cogman.py, predicators/execution_monitoring/base_execution_monitor.py
Online exploration in the forthcoming complex sticky table environment causes some issues with execution monitoring. Specifically, when we use the `expected_atoms` monitor, at the start of new online learning cycles, we end up accidentally remembering the monitoring info for old plans and trying to monitor w.r.t them. This PR makes a few minor changes to fix this issue.
=> Changes to fix execution monitoring in the online exploration case

predicators/utils.py, tests/test_utils.py
the case this fixes is where there is hierarchical typing, but some type that doesn't have any ancestors, and there are some objects of the latter type in problem files. for example:
```
(:types 
immovable movable - base-object
container - movable
robot
)
```
with `robot`
=> fix hierarchical typing edge case

predicators/explorers/active_sampler_explorer.py
This PR fixes a bug with the `task_repeat` exploration baseline for active sampler learning. Previously, the agent would keep trying to get to the goal. Once it hits it, it makes one single plan to get to the initial state. If/when this plan ever fails, it goes back to trying to achieve the goal. Now, the agent stubbornly tries to achieve both the initial state and goal until it succeeds.
Also, we raise a warning when the planning graph is incomplete, which can lead to all kind of strange bugs if someone unknowingly runs experiments given this is the case.
=> Fix + raise awareness of subtle bugs with active sampler exploration

predicators/approaches/grammar_search_invention_approach.py, predicators/settings.py, tests/approaches/test_nsrt_learning_approach.py
This PR implements a predicate invention approach that employs clustering to try to reverse engineer the clusters of segments that correspond to the oracle operators and select predicates that are add effects in those clusters, letting pnad_search downstream handle chainability and removing some extraneous predicates through backchaining that might cause overfitting issues.
The performance on the four tasks from the AAAI paper is illustrated below: 
The non-oracle clustering method:
```
NUM_TRAIN_TASKS    NUM_SOLVED AVG_NUM_PREDS AVG_TEST_TIME  AVG_NODES_CREATED   LEARNING_TIME  NUM_SEEDS
EXPERIMENT_ID
blocks_main_200demo     200.00 (0.00)  48.70 (1.27)  14.20 (0.60)   0.66 (0.19)  3074.73 (1223.38)  149.81 (38.48)         10
cover_main_200demo      200.00 (0.00)  49.20 (0.75)   9.80 …
```
=> Clustering via reverse engineering

predicators/args.py, predicators/cogman.py, predicators/perception/base_perceiver.py, predicators/perception/kitchen_perceiver.py, predicators/perception/sokoban_perceiver.py, predicators/perception/trivial_perceiver.py, tests/envs/test_sokoban.py, tests/test_main.py
this is because I want to render states from inside the spot perceiver, rather than having to render based on the unwieldy spot observations. i'll actually do that in a separate PR in the other repo. in general, it's nice to have the ability to render 'mental images' that are completely inside the agent, instead of rendering things in the environment alone.
=> add functionality for rendering videos within cogman, rather than within the environment

predicators/approaches/active_sampler_learning_approach.py, predicators/utils.py, tests/test_utils.py
=> fix rotation bug in rectangle random sampling

predicators/approaches/active_sampler_learning_approach.py, predicators/explorers/__init__.py, predicators/explorers/active_sampler_explorer.py, predicators/structs.py, scripts/configs/active_sampler_learning.yaml, tests/explorers/test_active_sampler_explorer.py
Previously, we always updated the competence estimator with new data. Now, we only do so if we actually sampled from the learned policy; we don't let exploration samples influence our competence estimate.
=> Fixes competence estimation for when we do epsilon-greedy exploration sampling

predicators/approaches/grammar_search_invention_approach.py, predicators/approaches/nsrt_learning_approach.py, predicators/utils.py, tests/approaches/test_grammar_search_invention_approach.py, tests/approaches/test_nsrt_learning_approach.py
As @ashayathalye and I are starting to do predicate invention with increasingly larger grammars, the time taken to just apply the grammar predicates to a dataset is getting significant and slowing down iteration time. This PR makes the `--load_atoms` and `--save_atoms` flags apply to the predicate grammar as well!
=> Enable saving and loading of predicate grammar atom datasets

predicators/envs/stick_button.py, predicators/ground_truth_models/stick_button/nsrts.py, predicators/ground_truth_models/stick_button/options.py, tests/envs/test_stick_button.py
There were a few conceptual issues in the environment and definitions of nsrts/options for stick button that I wanted to resolve to minimize confusing results when iterating on predicate invention. This PR closes #1626. 
**Summary of changes:**
- Operator RobotPressButton (and its option) had stick as an argument -- but the stick is never used or referenced by the operator or option, so I removed this. 
- Operators RobotMoveToButtonFromNothing and RobotMoveToButtonFromButton don't have stick as an argument, but access its state inside the evaluation of the predicate HandEmpty (which in turn calls the Grasped predicate's classifier). I added a new attribute for the robot (fingers) like we see in PaintingEnv and ToolsEnv and made HandEmpty's classifier look at that attribute. 
- Sometimes …
=> Fix some conceptual issues with StickButtonMovementEnv

predicators/args.py, predicators/datasets/demo_only.py, predicators/settings.py, predicators/utils.py, tests/datasets/test_datasets.py, tests/test_utils.py
For predicate invention with a video-language model, we need to pass in images of the demonstrations to the VLM. This PR adds the flag `--make_demo_images`, which puts image sequences of each demonstration inside `CFG.image_dir` for debugging purposes, analagous to how `--make_demo_videos` puts videos in `CFG.video_dir`.
=> Enable saving an image sequence of each demonstration

predicators/approaches/nsrt_learning_approach.py, tests/approaches/test_grammar_search_invention_approach.py
Previously, our approach would error out and die whenever we ran predicate invention via the newly-implemented txt file or img demos features. This is because segmentation called from `nsrt_learning_approach.py` tries to call `utils.abstract` on the proposed predicates, and can't (because they're VLM predicates and their classifiers haven't been implemented yet!). But of course, we know what the abstract states are for all the demonstrations, so this PR just passes that along correctly, and now `nsrt_learning` runs without erroring out!
=> fix segmentation error with predicate invention from txt files or img demos

predicators/datasets/generate_atom_trajs_with_vlm.py
Previously, we weren't labelling one of the atom proposal prompts with "Skills executed in trajectory" (rather, we directly just vomited the skills there out of context), and also we didn't parse out any predicates that had objects with `_` in them (because this didn't happen in our example!). This quick PR fixes these before I forget
=> fix some minor prompting + parsing issues

predicators/datasets/generate_atom_trajs_with_vlm.py
Mac creates these annoying `.DS_STORE` files that customize how the application "finder" displays folders. The current code for parsing the subfolders that hold images for each demonstration doesn't account for any other files being in the folder other than the `traj_<number>` files. Slight update to the code to make it not crash in these scenarios.
=> Fix parsing of trajectory demonstration subfolders for macs.

predicators/datasets/generate_atom_trajs_with_vlm.py, predicators/envs/kitchen.py, predicators/execution_monitoring/expected_atoms_monitor.py, predicators/perception/kitchen_perceiver.py, predicators/structs.py, predicators/utils.py, tests/test_utils.py
Implements a new `VLMPredicate` class that can be called at test time, makes sure that these are called during abstraction in a batched fashion (implements a new `utils` function for this), modifies execution monitor accordingly.
=> Test-time VLM Predicate evaluation

predicators/envs/kitchen.py
I was seeing this strange behavior where even though we're outputting good plans at test-time and executing them correctly, we fail to solve test-tasks from time to time. e.g. this command:
```
python predicators/main.py --env kitchen --approach grammar_search_invention --seed 0 --num_train_tasks 1 --num_test_tasks 1 --bilevel_plan_without_sim True --perceiver kitchen --offline_data_method demo_with_vlm_imgs --vlm_model_name gemini-1.5-pro-latest --segmenter every_step --grammar_search_vlm_atom_proposal_prompt_type options_labels_whole_traj --grammar_search_task_planning_timeout 10.0 --sesame_max_skeletons_optimized 200 --excluded_predicates all --disable_harmlessness_check True --debug --kitchen_goals boil_kettle --kitchen_use_perfect_samplers True …
```
=> Fix annoying kitchen test time bug

predicators/ground_truth_models/kitchen/nsrts.py, predicators/ground_truth_models/kitchen/options.py, predicators/settings.py, predicators/structs.py
One annoying thing about VLM-based predicate invention in kitchen is that the VLM is seemingly bad at labelling atom values after moving (because the arm introduces occlusions, etc. in a bunch of places). This PR introduces some new NSRTs and options that move the arm implicitly (e.g. instead of having separate `MoveToTurnOn` and `TurnOn` NSRTs, we now have one `MoveAndTurnOn` NSRT). The PR also introduces a new command line flag to toggle this on or or off. Currently, this is only implemented for `TurnOn` and `Push` skills, but will likely be extended to more in the future!
=> Making "combined" options and NSRT's for kitchen

predicators/datasets/generate_atom_trajs_with_vlm.py, predicators/envs/burger.py, predicators/envs/kitchen.py, predicators/perception/kitchen_perceiver.py, predicators/pretrained_model_interface.py, predicators/utils.py, tests/datasets/test_datasets.py, tests/envs/test_burger.py, tests/test_utils.py
Before we can get geometric + VLM predicate invention working in BurgerEnv, we need VLM predicate invention without geometric predicates working in BurgerEnv. This PR gets VLM predicate invention to run in BurgerEnv -- it does not yet work well (the predicate proposals are decent but the labeling isn't good enough yet) -- but at least it runs: we see `Cooked` and `Holding` generated as VLM predicates, but `Cooked` is not labeled accurately. 
For example, you can run `python predicators/main.py --env burger --approach grammar_search_invention --seed 0 --num_train_tasks 1 --num_test_tasks 1 --bilevel_plan_without_sim True --offline_data_method demo_with_vlm_imgs --vlm_model_name gemini-1.5-pro-latest --segmenter every_step --grammar_search_vlm_atom_proposal_prompt_type …
=> Support VLM predicate invention in BurgerEnv

predicators/envs/base_env.py, predicators/envs/burger.py, predicators/main.py, predicators/settings.py, predicators/structs.py, predicators/utils.py, tests/test_structs.py, tests/test_utils.py
When doing VLM predicate invention, we may want to invent goal predicates. In this case, we need some alternative way to describe the goal for the agent than the normal goal predicates. One (slightly hacky?) thing we can do is have a new goal predicate that evaluates to True when all of the actual goal predicates evaluate to True. We can't also have the demonstrator use this new goal predicate as their goal, because the oracle operators are defined in terms of the original goal predicates. Rather than rewrite the oracle operators in terms of this hacky new goal predicate, it makes sense to instead provide a way for the tasks to be in terms of different goal predicates for the agent versus the demonstrator. 
Conceptually, this seems ok. The demonstrator solved some tasks with some goals in …
=> Allow different task goals for demonstrator vs agent

predicators/approaches/bridge_policy_approach.py, predicators/approaches/grammar_search_invention_approach.py, predicators/datasets/__init__.py, predicators/envs/base_env.py, predicators/envs/burger.py, predicators/main.py, predicators/settings.py, predicators/structs.py, predicators/utils.py, tests/approaches/test_grammar_search_invention_approach.py, tests/envs/test_burger.py, tests/test_structs.py, tests/test_utils.py
This basically just calls both the method to generate predicates from a grammar and the method to generate predicates from a VLM and then combines the atom datasets produced by both. 
This does not yet work "well" in BurgerEnv yet because we don't get the predicates we want in the grammar (we'll have to tweak the grammar a bit, and also be careful about what predicates we include/exclude). But the pipeline works in that the atom datasets are combined properly into something with both geometric and VLM ground atoms.
An important change in this is that we now make it possible to replace goal predicates (e.g. goal predicates that we might expect the demonstrator to use) with agent-specific goal predicates -- which is relevant when we want the agent to invent the corresponding goal predicate …
=> Enable predicate invention with both geometric and VLM predicates

predicators/approaches/bridge_policy_approach.py, predicators/approaches/maple_q_approach.py, predicators/explorers/maple_q_explorer.py, predicators/ml_models.py
A CallPlanner NSRT was added to RLBridgePolicyApproach, which does not change the low-level environment state but transfers control back to the planner. Bridge policy can use this NSRT to call the planner, allowing the method to resume online bilevel planning after the bridge policy is executed.
=> Added CallPlanner action to RL_Bridge_Policy

predicators/main.py
Previously, in `main.py`, we 
- Replaced goal predicates with agent-specific goal predicates whenever the environment defined these, and these were passed into the approach's initial predicates (which messes up oracle's ground truth operators)
- Replaced task goals with alternative goals whenever the environment defined these (but oracle's ground truth operators won't usually be in terms of the alternative goals)
both of which caused oracle approach to not work at *test* time in BurgerEnv (it worked fine at train time). 
Now we make these two replacements only happen when the approach is not oracle. 
For example, now `python predicators/main.py --env burger --approach oracle --seed 0 --num_train_tasks 1 --num_test_tasks 1 --option_model_terminate_on_repeat False …
=> Fix oracle approach on test tasks when an environment defines alternative goals and agent-specific goal predicates

predicators/envs/burger.py, tests/envs/test_burger.py
Modifies agent goals, etc. such that we have an 'end-to-end' result in burger for the first time!
```
python predicators/main.py --env burger_no_move --approach grammar_search_invention --seed 0 --num_train_tasks 8 --num_test_tasks 3 --bilevel_plan_without_sim True --offline_data_method geo_and_demo_with_vlm_imgs --vlm_model_name gpt-4o --segmenter option_changes --grammar_search_vlm_atom_proposal_prompt_type options_labels_whole_traj_diverse --grammar_search_vlm_atom_label_prompt_type img_option_diffs_label_history_burger --grammar_search_task_planning_timeout 10.0 --sesame_max_skeletons_optimized 200 --disable_harmlessness_check True --sesame_task_planner fdopt --excluded_predicates all --option_model_terminate_on_repeat False --grammar_search_vlm_atom_proposal_use_debug False …
```
=> Fix burger agent goals towards getting an 'end-to-end' result

predicators/approaches/grammar_search_invention_approach.py
Previously, the `--load_approach` flag was broken for grammar search invention. This is because the `_learned_predicates` was not being set: we just needed to do that.
=> Gets `--load_approach` to work for grammar search invention
