src/main.py
src/structs.py
tests/approaches/test_random_actions_approach.py
tests/approaches/test_random_options_approach.py

Closes #60 
@ronuchit please review

seed boxes

---

src/approaches/interactive_learning_approach.py
src/structs.py
tests/approaches/test_interactive_approach.py

Fixes:
- make sure student only asks about predicates to learn
- for states that have no ground atoms samples, just have an empty set instead of failing
- new dataset type to better ensure that # states = # set of ground atoms in each trajectory

Active learning bugs

---

src/structs.py
src/utils.py
tests/test_structs.py

should make A* search at the task-level completely deterministic and reproducible given a particular seed.

modifies A* search to make task-planning seeded-deterministic!

---

src/approaches/iterative_invention_approach.py
src/nsrt_learning.py
src/structs.py
src/utils.py
tests/test_utils.py

this will make life easier when implementing the approaches described here:
https://docs.google.com/document/d/1O7IqkUz6KCIlG7dZy4GJ8D40kVnuksKG6bzLzLeVQxQ/edit
also, the new utility may be useful for @amburger66 (or not, not sure)

small refactor to abstract before segmenting 

---

src/structs.py
tests/test_structs.py

also will be useful for invention

ground strips operators

---

src/utils.py
tests/test_utils.py

will be useful for new invention approach

add gbfs util

---

src/approaches/grammar_search_invention_approach.py
src/nsrt_learning.py
src/settings.py
src/utils.py
tests/approaches/test_nsrt_learning_approach.py
tests/test_utils.py

and a few other minor changes, e.g., to printing

allow search over predicate sets from small to large

---

src/approaches/iterative_invention_approach.py
src/nsrt_learning.py
tests/approaches/test_nsrt_learning_approach.py
tests/test_nsrt_learning.py

use options to segment when they are available

---

.coveragerc
src/approaches/grammar_search_invention_approach.py
src/settings.py
tests/approaches/test_grammar_search_invention_approach.py
tests/approaches/test_nsrt_learning_approach.py

should be merged after #136 and #137

new grammar with forall quantifiers

---

src/approaches/oracle_approach.py
src/envs/__init__.py
src/envs/painting.py
src/option_learning.py
src/settings.py
tests/approaches/test_oracle_approach.py
tests/envs/test_base_env.py
tests/envs/test_painting.py
tests/test_option_learning.py

painting environment

---

requirements.txt

* (sorry I accidentally deleted earlier!)

revives old requirements.txt

---

src/envs/cover.py
src/envs/painting.py
tests/envs/test_painting.py

basic plt render for painting

---

src/approaches/grammar_search_invention_approach.py
src/envs/blocks.py
tests/approaches/test_grammar_search_invention_approach.py
tests/envs/test_blocks.py

Closes #159
and should be merged after #163

Remove clear bit from blocks and update predicate grammar accordingly

---

src/approaches/nsrt_learning_approach.py
src/nsrt_learning.py

 seed learned option parameter spaces 

---

src/approaches/grammar_search_invention_approach.py
src/approaches/interactive_learning_approach.py
src/datasets/demo_only.py
src/datasets/demo_replay.py
src/nsrt_learning.py
src/option_model.py
src/structs.py
src/utils.py
tests/approaches/test_grammar_search_invention_approach.py
tests/approaches/test_interactive_approach.py
tests/datasets/test_datasets.py
tests/envs/test_cover.py
tests/envs/test_playroom.py
tests/test_nsrt_learning.py
tests/test_option_learning.py
tests/test_sampler_learning.py
tests/test_structs.py
tests/test_utils.py

This new class contains goals.

refactor StateActionTrajectory into its own class called LowLevelTrajectory

---

src/main.py

this is one of a few PRs that I am going to make so that we can automatically generate the proxy analysis tables

have run_testing return results dict so we can more easily save it

---

src/envs/repeated_nextto.py
src/planning.py
src/structs.py
tests/test_planning.py
tests/test_structs.py

possible path toward addressing planning (half of #175)
@ronuchit @NishanthJKumar @wmcclinton

possible way to address repeatednextto

---

src/envs/repeated_nextto.py
src/planning.py
src/structs.py
tests/test_planning.py
tests/test_structs.py

Reverts Learning-and-Intelligent-Systems/predicators#192

Revert "possible way to address repeatednextto"

---

src/approaches/grammar_search_invention_approach.py
src/option_model.py
src/planning.py
src/settings.py
src/utils.py
tests/approaches/test_grammar_search_invention_approach.py
tests/test_utils.py

we know that this is bad (see unit test), but we want to include it for completeness

 task planning heuristic for grammar search approach 

---

src/utils.py
tests/test_utils.py

oops, fyi @ronuchit @amburger66

fix hmax edge case with empty operator preconditions

---

src/approaches/oracle_approach.py
src/envs/playroom.py
src/settings.py
tests/approaches/test_oracle_approach.py
tests/envs/test_playroom.py

* added oracle NSRTs for playroom env
* `test_oracle_approach_playroom` doesn't work right now because planning is hard; right now the approach works if all the door start out open

Playroom env oracle approach

---

src/approaches/iterative_invention_approach.py
src/nsrt_learning.py
src/planning.py
src/structs.py
src/utils.py
tests/test_utils.py

get rid of redundant code via smarter mypy typing

---

.gitignore
README.md
analysis/analyze_supercloud_experiments.py
analysis/run_supercloud_experiments.sh
analysis/submit.py
mypy.ini
src/main.py
src/planning.py
src/structs.py
src/utils.py
tests/approaches/test_grammar_search_invention_approach.py
tests/test_structs.py
tests/test_utils.py

should help with easier parallelized testing of our main pipeline to make sure there are no regressions / check for slowdowns!

enable running experiments on supercloud

---

analysis/grammar_search_analysis.py
src/approaches/grammar_search_invention_approach.py
src/settings.py
tests/approaches/test_grammar_search_invention_approach.py

switch grammar_search_score_function to hff_lookahead_depth1

---

src/envs/playroom.py
tests/envs/test_playroom.py

- robot should not be able to do some other action (e.g. picking a block, opening a door, toggling the dial) after moving to a new location

Playroom simulator bug fix

---

analysis/analyze_supercloud_experiments.py
src/main.py
src/settings.py
tests/test_main.py

@NishanthJKumar this will make it so you don't need that pragma: no cover in main.py

fix local coverage issue in main.py

---

src/approaches/grammar_search_invention_approach.py
src/approaches/iterative_invention_approach.py
src/approaches/nsrt_learning_approach.py
src/datasets/demo_only.py
src/datasets/demo_replay.py
src/nsrt_learning.py
src/option_learning.py
src/sampler_learning.py
src/settings.py
tests/approaches/test_nsrt_learning_approach.py
tests/datasets/test_datasets.py
tests/test_main.py
tests/test_nsrt_learning.py
tests/test_option_learning.py

addresses the first half of #246

remove do_*_learning flags

---

src/structs.py
tests/test_structs.py

Adds gt and lt methods for ParameterizedOptions

---

src/approaches/grammar_search_invention_approach.py
src/main.py
src/settings.py
src/utils.py
tests/test_utils.py

generalizes hill climbing to keep searching even if no immediate improvement can be found
it's very slow with depth>0, as you can imagine. i'm not sure if will use this, or if it's better than GBFS, but maybe? it can't hurt to have in our arsenal...

enforced hill climbing

---

analysis/analyze_supercloud_experiments.py
analysis/grammar_search_analysis.py
src/main.py
src/structs.py

redo & consolidate evaluation metrics, now we have:
* num test tasks solved
* num test tasks total
* average test time for _successes_
* average number of node expansions for problems where a plan is found
* average plan length for problems where a plan is found
* total learning time

new evaluation metrics

---

src/structs.py

Sorry for the premature merge earlier :( @tomsilver

make options not frozen

---

src/envs/behavior.py
src/envs/behavior_options.py

* splits off functions that return policy function so integrating option model will be significantly easier
* includes some helpful status prints within option execution
* renames behavior_env attr of BehaviorEnv to igibson_behavior_env to be clearer

refactors behavior_options.py

---

src/envs/behavior.py
src/envs/behavior_options.py
src/option_model.py

Sets up interface (i.e, `_BehaviorOptionModel` in `option_models.py`) as well as option models (included in `behavior_options.py`) for BEHAVIOR!
Planning time is significantly faster (though still cannot solve test task due to sampler/other issues that will be addressed in a separate PR). Bottleneck is no longer `env.step()` calls, but rather time between option model executions (roughly 1 min between each action).

Sets up interface and incorporates option models for BEHAVIOR!

---

src/approaches/interactive_learning_approach.py
src/settings.py
tests/approaches/test_interactive_approach.py

- changed the ask strategy so robot cannot ask teacher about past states: for each state in a newly-explored trajectory, the robot considers each possible ground atom and queries the teacher about the atoms that score higher than the best atom seen previously (note that this is currently flawed b/c the robot will only ask in the first state and never again)
- updated settings

Interactive learning approach

---

src/approaches/interactive_learning_approach.py
src/datasets/demo_only.py
src/envs/painting.py
src/envs/playroom.py
src/main.py
src/nsrt_learning.py
src/settings.py
src/structs.py
src/utils.py
tests/approaches/test_grammar_search_invention_approach.py
tests/envs/test_cover.py
tests/envs/test_playroom.py
tests/test_main.py
tests/test_nsrt_learning.py
tests/test_option_learning.py
tests/test_option_model.py
tests/test_planning.py
tests/test_structs.py
tests/test_utils.py

no changes to any API or user usage. this PR quickly got out of
control..... :(

refactor utils policy-running methods; fix option semantics in one-step case

---

mypy.ini
requirements.txt
src/approaches/grammar_search_invention_approach.py
src/settings.py
src/utils.py
tests/test_utils.py

it's significantly slower on my machine (2-5x slower) on both cover and
painting with grammar_search_invention approach, so leaving this
disabled for now, but the code is here if we ever want to enable it in
the future
closes #264

option to parallelize hill climbing

---

src/main.py
src/planning.py

this used to happen, but got clobbered by the reorganization for supercloud

print out testing results

---

analysis/grammar_search_analysis.py
analysis/submit.py
src/approaches/interactive_learning_approach.py
src/datasets/demo_only.py
src/envs/blocks.py
src/envs/playroom.py
src/main.py
src/utils.py
tests/approaches/test_nsrt_learning_approach.py
tests/approaches/test_oracle_approach.py
tests/envs/test_cluttered_table.py
tests/envs/test_cover.py
tests/envs/test_playroom.py
tests/test_planning.py

it's more efficient to just check that every goal atom holds

clean up instances of unnecessary calls to issubset() for goal checking

---

src/approaches/grammar_search_invention_approach.py
tests/approaches/test_grammar_search_invention_approach.py

to allow better distinguishability from self._initial_predicates

minor renaming predicates -> candidate_predicates

---

src/approaches/interactive_learning_approach.py
tests/approaches/test_interactive_approach.py

a better way for the teacher to pick which ground atoms to comment on while adhering to `teacher_dataset_label_ratio` as closely as possible. now ensures the ratio for each predicate even when multiple predicates are being learned

Interactive approach: modified teacher dataset creation

---

src/approaches/base_approach.py
src/approaches/tamp_approach.py

initialization needs to be inside `BaseApproach.reset_metrics()` which is called before every test run

Fix metrics `min_skeletons_optimized`

---

src/planning.py
src/utils.py
tests/test_main.py
tests/test_utils.py

handle more argument types for cmd line

---

src/settings.py
src/utils.py
tests/approaches/test_interactive_approach.py
tests/approaches/test_nsrt_learning_approach.py
tests/approaches/test_oracle_approach.py

* don't need to pass in duplicated env/approach/seed
* experiment_id is optional

update_config() updates

---

analysis/run_supercloud_experiments.sh

5->10 seeds supercloud

---

src/approaches/grammar_search_invention_approach.py

result of exploration into making painting downward refinable with a learned AllLidsOpen predicate

minor: add preds to painting debug grammar

---

src/approaches/base_approach.py
src/args.py
src/datasets/demo_replay.py
src/envs/__init__.py
src/envs/base_env.py
src/envs/cluttered_table.py
src/envs/painting.py
src/envs/playroom.py
src/main.py
src/planning.py
src/settings.py
src/utils.py
tests/approaches/test_oracle_approach.py
tests/envs/test_base_env.py
tests/envs/test_cluttered_table.py
tests/envs/test_painting.py
tests/envs/test_playroom.py
tests/test_main.py
tests/test_utils.py

make videos of failed planning attempts, for debugging etc
this is heavily heavily based on @ashayathalye 's code (#344 ) with changes mostly to get checks passing

Make failure videos

---

analysis/grammar_search_analysis.py
src/approaches/grammar_search_invention_approach.py
src/approaches/interactive_learning_approach.py
src/approaches/iterative_invention_approach.py
src/approaches/nsrt_learning_approach.py
src/datasets/demo_only.py
src/datasets/demo_replay.py
src/main.py
src/nsrt_learning.py
src/structs.py
src/utils.py
tests/approaches/test_grammar_search_invention_approach.py
tests/approaches/test_interactive_approach.py
tests/datasets/test_datasets.py
tests/test_option_learning.py

change Dataset from List[LowLevelTrajectory] to a dataclass. this is in preparation for refactoring the dataset creation for interactive_learning so that it happens in datasets/ rather than in the approach itself. that change isn't in this PR though; that will happen next.

Dataset refactor

---

analysis/grammar_search_analysis.py
src/approaches/__init__.py
src/approaches/base_approach.py
src/approaches/grammar_search_invention_approach.py
src/approaches/interactive_learning_approach.py
src/approaches/iterative_invention_approach.py
src/approaches/nsrt_learning_approach.py
src/approaches/tamp_approach.py
src/datasets/demo_only.py
src/datasets/demo_replay.py
src/main.py
src/structs.py
tests/approaches/test_base_approach.py
tests/approaches/test_grammar_search_invention_approach.py
tests/approaches/test_interactive_approach.py
tests/approaches/test_nsrt_learning_approach.py
tests/approaches/test_oracle_approach.py
tests/approaches/test_random_actions_approach.py
tests/approaches/test_random_options_approach.py
tests/test_main.py
tests/test_online_learning.py
tests/test_planning.py
tests/test_structs.py

and replace goals with train task idxs in lowleveltrajectory

initialize approaches with train tasks 

---

src/approaches/interactive_learning_approach.py
src/datasets/__init__.py
src/datasets/ground_atom_data.py
src/settings.py
src/structs.py
tests/approaches/test_interactive_approach.py
tests/datasets/test_datasets.py

I think this is mostly done, but I may have discovered a bug in interactive_learning_approach that I want to clear up before we merge (checking with @amburger66 offline if my understanding is correct).

new dataset type and refactoring offline part of interactive_learning_approach

---

src/torch_models.py
tests/test_models.py

take a shortcut for classification with only one class in data

---

src/main.py
tests/test_main.py
tests/test_online_learning.py

another bug created by me and found by @amburger66 😬

fix crash in data generation when goal predicates excluded

---

analysis/analyze_results_directory.py
src/main.py

@amburger66 sorry for all the fluctuations/wrinkles in the code recently, hope this is what you had in mind for fixing your issue
also updated the results script to not crash, and gave it a better name
closes #390

don't use num_transitions in results filenames

---

src/datasets/demo_only.py

prevents occasional crashes in cluttered_table, where our oracle can fail due to loops

demo generation is allowed to fail, emits a warning

---

src/envs/__init__.py
src/envs/cover.py
src/ground_truth_nsrts.py
tests/approaches/test_oracle_approach.py
tests/envs/test_base_env.py
tests/envs/test_cover.py

https://user-images.githubusercontent.com/2816502/151999138-3a07764b-1006-497e-b8d6-012dc78a671b.mp4

nonrefinable variant of cover environment

---

src/envs/blocks.py

blocks: all picks are to a fixed height

---

analysis/grammar_search_analysis.py
src/approaches/grammar_search_invention_approach.py
src/settings.py
tests/approaches/test_grammar_search_invention_approach.py

after merging this, will update supercloud-vary-score-function branch

ExpectedNodesScoreFunction can use either nodes_created or nodes_expanded

---

src/approaches/grammar_search_invention_approach.py

tested by adding `Forall[1:box].[InBox(0,1)]` into the debug grammar and verifying that it gets pruned out by the new code

hack: filter out invented predicates not appearing in any precondition

---

src/approaches/interactive_learning_approach.py
src/main.py
src/settings.py
src/structs.py
src/teacher.py
tests/approaches/test_interactive_approach.py
tests/test_online_learning.py
tests/test_settings.py
tests/test_teacher.py

Implements demonstration query and response for use with DAgger-like methods!

Demonstration Query and Response

---

tests/approaches/test_oracle_approach.py

@tomsilver i wanted to do this but cover_regrasp is failing to plan. related to #417 perhaps?

speed up oracle testing

---

tests/datasets/test_datasets.py

I think this test was just flaky. this seems to fix it.

fix flaky dataset test

---

analysis/run_supercloud_experiments.sh
src/envs/__init__.py
src/envs/blocks.py
src/envs/painting.py
src/envs/playroom.py
src/envs/tools.py
src/ground_truth_nsrts.py
src/settings.py
src/utils.py
tests/approaches/test_oracle_approach.py
tests/envs/test_base_env.py
tests/envs/test_playroom.py
tests/envs/test_tools.py
tests/test_utils.py

tested that both oracle and nsrt_learning work well on supercloud

tools environment

---

src/approaches/grammar_search_invention_approach.py
src/envs/tools.py
src/ground_truth_nsrts.py
src/settings.py
tests/approaches/test_grammar_search_invention_approach.py
tests/envs/test_tools.py

simplifications to env:
* remove OnTable predicates and on_table low-level features
* remove contraption upper bound features, since size is fixed
confirmed that DebugGrammar predicates are all included in our full
grammar with `grammar_search_max_predicates 200`

simplify tools env and add in DebugGrammar

---

src/datasets/demo_replay.py
src/ground_truth_nsrts.py
src/planning.py
src/sampler_learning.py
src/structs.py
src/utils.py
tests/approaches/test_oracle_approach.py
tests/test_nsrt_learning.py
tests/test_planning.py
tests/test_structs.py
tests/test_utils.py

goal-conditioned sampler API update

---

src/approaches/grammar_search_invention_approach.py
src/utils.py
tests/test_utils.py

example printout:
```
Hill climbing summary:
On step 1, added NOT-((0:block).pose_z<=[idx 0]0.875), with
heuristic 2300430.068 (an improvement of 720802.285 over the previous
step)
On step 2, added Forall[0:block].[NOT-On(0,1)], with heuristic
722064.088 (an improvement of 1578365.981 over the previous step)
On step 3, added NOT-((0:robot).fingers<=[idx 0]0.5), with
heuristic 2501.139 (an improvement of 719562.949 over the previous step)
```
closes #428

before filtering out predicates, print out hill climbing summary

---

analysis/analyze_results_directory.py
analysis/create_online_learning_curves.py

@amburger66 I'm hoping this can be useful for you too!
example outputs (don't worry about what the content means, probably garbage):

online learning curve script

---

README.md
analysis/skeleton_score_analysis.py
src/approaches/grammar_search_invention_approach.py
src/approaches/tamp_approach.py
src/planning.py
src/settings.py
tests/approaches/test_grammar_search_invention_approach.py
tests/test_main.py
tests/test_planning.py

* task_planning_heuristic -> sesame_task_planning_heuristic
* max_skeletons_optimized -> sesame_max_skeletons_optimized
* max_samples_per_step -> sesame_max_samples_per_step

rename some settings for clarity

---

src/approaches/interactive_learning_approach.py
src/datasets/__init__.py
src/datasets/ground_atom_data.py
src/settings.py
tests/approaches/test_interactive_approach.py
tests/datasets/test_datasets.py

so the focus is on active learning now! for the offline dataset, there is just one hyperparameter that controls the # of pos examples and # of neg examples for each predicate (e.g. `teacher_dataset_num_examples=1` means there is 1 positive and 1 negative annotated example for each excluded predicate)

Semi-supervised is dead

---

src/approaches/random_options_approach.py
src/planning.py
src/utils.py
tests/approaches/test_random_options_approach.py
tests/test_structs.py
tests/test_utils.py

and standardize to use `DefaultState` instead of `State({})`

fix crash in random_options + tools

---

analysis/analyze_results_directory.py
analysis/create_latex_tables.py
analysis/create_plots.py

generate latex tables from results directory

---

requirements.txt

until we figure out what the heck happened in yesterday's release

downgrade gym

---

src/settings.py
tests/nsrt_learning/test_sampler_learning.py

* because we want to be able to say in papers that we are robust to non unimodal stuff

disable disabling the sampler classifier

---

src/nsrt_learning/sampler_learning.py
tests/nsrt_learning/test_sampler_learning.py

I don't think this matters for anything anytime soon, but was in this part of the code, and thought this implementation makes more sense.

clip regressor outputs when classifier is disabled

---

src/utils.py
tests/test_utils.py

Duplicate of https://github.com/Learning-and-Intelligent-Systems/predicators/pull/494 but on a branch on the main repository

Add Goal Count Heuristic

---

src/main.py
src/utils.py

@ronuchit I fell down a bit of a rabbit hole and now I'm not sure if this was necessary for the other changes I'm making, but I still think this is better, because it keeps the act_policy and query_policy in lockstep.

Interaction loop refactor

---

tests/test_main.py

back down to about 65s after this change

fix ~12s slowdown related to interactive_num_ensemble_members in test_main.py

---

analysis/grammar_search_analysis.py
analysis/skeleton_score_analysis.py
src/envs/__init__.py
src/ground_truth_nsrts.py
src/main.py
src/nsrt_learning/option_learning.py
src/nsrt_learning/sampler_learning.py
src/option_model.py
src/settings.py
src/teacher.py
tests/approaches/test_nsrt_learning_approach.py
tests/approaches/test_oracle_approach.py
tests/datasets/test_datasets.py
tests/envs/test_base_env.py
tests/nsrt_learning/test_option_learning.py
tests/test_online_learning.py
tests/test_predicate_search_score_functions.py
tests/test_teacher.py

Reverts Learning-and-Intelligent-Systems/predicators#507
- testing single files is broken
- the option model thing that we discussed is another signal that this solution isn't ideal

Revert "change create_env to get_cached_env_instance in ground truth nsrts"

---

src/envs/blocks.py
src/envs/painting.py
src/envs/playroom.py
src/ground_truth_nsrts.py
tests/envs/test_painting.py
tests/envs/test_playroom.py

tested painting and playroom oracle and nsrt_learning

remove some silly parameters from options in painting/playroom

---

src/approaches/interactive_learning_approach.py

it wasn't working because `self._pred_to_ensemble` wasn't getting saved/loaded

Fix load interactive learning approach

---

src/envs/base_env.py
src/envs/behavior.py
src/envs/blocks.py
src/envs/cluttered_table.py
src/envs/cover.py
src/envs/painting.py
src/envs/playroom.py
src/envs/repeated_nextto.py
src/envs/tools.py
tests/envs/test_blocks.py
tests/envs/test_cluttered_table.py
tests/envs/test_cover.py
tests/envs/test_painting.py
tests/envs/test_playroom.py
tests/envs/test_repeated_nextto.py

I'll use this to render videos labeled with query responses during active learning, and it could be used for other purposes too

Add an optional caption to `render` and `render_state`

---

src/envs/cover.py
src/settings.py

fix nsrt learning with cover-multistep-options

---

src/envs/blocks.py
src/envs/playroom.py
src/ground_truth_nsrts.py
src/settings.py
tests/nsrt_learning/test_option_learning.py
tests/test_predicate_search_score_functions.py

* a number of changes to the dimensions to make them physically realistic
* changing the robot features to include pose, which is needed for the options in pybullet
* several other minor tweaks, mostly for clarity

changes to blocks env in advance of pybullet blocks env 

---

src/envs/blocks.py
src/envs/playroom.py
src/settings.py
tests/nsrt_learning/test_option_learning.py
tests/test_predicate_search_score_functions.py

Reverts Learning-and-Intelligent-Systems/predicators#537
at least one bad seed found on supercloud, reverting until we investigate...

Revert "changes to blocks env in advance of pybullet blocks env "

---

src/approaches/grammar_search_invention_approach.py

* featuring a hackily written if statement to ensure coverage lol
* tested all other debug grammars, they are fine

fix blocks debug grammar and allow pybullet debug grammars

---

README.md
requirements-dev.txt
scripts/run_checks.sh

requirements dev

---

tests/test_structs.py

* verified via print statement that test_state() is only called once
closes #559

add simple example of using fixture for test_structs

---

scripts/run_predicators_baseline_experiments.sh
scripts/run_predicators_num_demos_experiments.sh

should we actually merge this into master? I don't see why not?

add main script experiments

---

scripts/create_plots.py

add gnn to plot script

---

scripts/grammar_search_analysis.py
scripts/skeleton_score_analysis.py
src/approaches/base_approach.py
src/envs/base_env.py
tests/approaches/test_oracle_approach.py
tests/approaches/test_random_actions_approach.py
tests/approaches/test_random_options_approach.py
tests/envs/test_blocks.py
tests/envs/test_cluttered_table.py
tests/envs/test_cover.py
tests/envs/test_painting.py
tests/envs/test_playroom.py
tests/envs/test_pybullet_blocks.py
tests/envs/test_repeated_nextto.py
tests/envs/test_tools.py
tests/nsrt_learning/test_option_learning.py
tests/test_planning.py
tests/test_utils.py

change approach and env seed to _set_seed and remove seed(123) in tests

---

scripts/supercloud/run_sidelining_experiments.sh

even though we don't really expect this baseline to do well, I think it's good/useful to have it in this script to compare new approaches against!

adds harmlessness based baseline to sidelining expers

---

src/envs/cover.py

can be replicated locally with `pip install --upgrade pylint`

fix lint error caused by pylint upgrade

---

src/approaches/grammar_search_invention_approach.py
tests/approaches/test_grammar_search_invention_approach.py

fix edge case in single features inequality grammar

---

src/envs/pybullet_blocks.py
src/envs/pybullet_robots.py
src/settings.py
tests/envs/test_pybullet_robots.py

in preparation for adding another (panda) robot.
this is definitely not the last refactoring we will do, and we'll probably realize things in the course of adding the new robot, but this is a start.

factor out robot from pybullet blocks env

---

src/envs/pddl_env.py
src/ground_truth_nsrts.py
src/option_model.py

remove a few uses of `cast`

---

src/utils.py
tests/test_utils.py

add `create_state_from_dict` utility

---

src/envs/blocks.py
src/envs/cover.py
src/envs/painting.py
src/envs/playroom.py
src/envs/pybullet_blocks.py
src/envs/pybullet_robots.py
src/envs/repeated_nextto.py
src/envs/tools.py
src/utils.py

add ClassVar annotations to all class variables

---

README.md
behavior.md

factor out behavior stuff from readme

---

src/nsrt_learning/side_predicate_learning.py
src/nsrt_learning/strips_learning.py
src/utils.py
tests/test_utils.py

utility for generating fresh variables

---

src/nsrt_learning/side_predicate_learning.py

no functionality changes. we generally avoid "hl_state" (after this
change, `git grep "hl_state" | wc -l` gives 0) in favor of "atoms". also
some consistency issues and confusion with state as in search state vs
state as in atoms

minor naming changes to side predicate learning file

---

src/nsrt_learning/side_predicate_learning.py

* fix incorrect usage of `ll_traj.actions` (which doesn't matter in
current envs, but would break in envs with multistep option policies)
* allow noops in call to `task_plan_grounding()` in harmlessness check,
because we want to consider operators like OpenLid in painting. note
that the planner would use such operators, only because of the
DiscoveredFailure stuff...sigh
* the most general PNADs now have preconditions computed via an
intersection, so that these operators are better than before. specifically,
this helps the OpenLid operator: it never gets specifized, but we still
want GripperOpen to appear in its precondition

fix a bunch of bugs in sidelining

---

src/envs/touch_point.py
src/ground_truth_nsrts.py
src/settings.py
tests/approaches/test_oracle_approach.py
tests/envs/test_base_env.py
tests/envs/test_touch_point.py

example with random actions:
https://user-images.githubusercontent.com/2816502/161387887-a4d97626-5993-4392-b08b-81c3b6cf7cce.mp4
example with learned nsrts:
https://user-images.githubusercontent.com/2816502/161387868-e5ad0330-f371-467a-921d-900851d056b6.mp4
things that I tested:
* random actions
* random options
* oracle
* nsrt learning

toy touch point environment for option learning

---

src/approaches/interactive_learning_approach.py

(splitting up #652 into multiple smaller PRs)

use interaction data to learn nsrts

---

src/main.py
src/utils.py
tests/test_utils.py

make videos for execution failures when requested

---

scripts/create_interactive_predicate_learning_plots.py

Closes #669 
Example outputs:
and with `PLOT_TYPE = 'seed_lines'`:

plotting updates for interactive approach

---

src/approaches/interactive_learning_approach.py
src/nsrt_learning/option_learning.py
src/nsrt_learning/sampler_learning.py
src/settings.py
src/torch_models.py
tests/nsrt_learning/test_option_learning.py
tests/nsrt_learning/test_sampler_learning.py
tests/test_torch_models.py

cleaning up the torch models file. there should be NO functional changes. highlights:
* removed a lot of redundant code, especially the training loops
* added a few new base classes
* removed all occurrences of CFG to promote modularity

large refactor of torch models file

---

src/nsrt_learning/option_learning.py
src/settings.py
src/torch_models.py
tests/test_torch_models.py

`python src/main.py --approach nsrt_learning --env touch_point --option_learner implicit_bc --implicit_mlp_regressor_inference_method grid` 50/50 on the first 5 seeds

grid method for implicit regressor inference

---

src/envs/cover.py
src/ground_truth_nsrts.py
tests/approaches/test_oracle_approach.py
tests/envs/test_base_env.py
tests/envs/test_cover.py

aka yet another cover environment

cover multistep options with holding goals

---

mypy.ini
requirements.txt
src/approaches/interactive_learning_approach.py
src/ml_models.py
src/nsrt_learning/option_learning.py
src/nsrt_learning/sampler_learning.py
tests/nsrt_learning/test_option_learning.py
tests/nsrt_learning/test_sampler_learning.py
tests/test_ml_models.py

* renames `torch_models` to `ml_models`
* add another layer of abstraction in the base classes for normalization
* add sklearn models
* update requirements.txt and mypy config for this new dependency
* should help with #685, but to close that issue, we will need to make changes in interactive learning approach too

more refactoring and updates to machine learning models

---

src/envs/painting.py
tests/envs/test_repeated_nextto_painting.py

necessary to get learned samplers to work in this environment!

fix that snaps objects onto the table surface in rnt-painting

---

src/envs/behavior_options.py
src/nsrt_learning/strips_learning/gen_to_spec_learner.py
tests/nsrt_learning/strips_learning/test_gen_to_spec_learner.py

Adds the datastore length check back to `_try_specializing_pnad` method for backchaining. Also adds a test that distinguishes this change.

Datastore len check fix

---

src/envs/pybullet_blocks.py
src/envs/pybullet_robots.py
src/envs/pybullet_utils.py
tests/envs/test_pybullet_blocks.py
tests/envs/test_pybullet_robots.py

so that we can use joint states within the forthcoming new controllers (which will perform planning in joint space), without changing the object-centric state exposed to the rest of the system

implement _PyBulletState subclass of State

---

src/envs/pybullet_blocks.py
src/envs/pybullet_robots.py
tests/envs/test_pybullet_robots.py

* move the action space into the robot
* expose the joint finger indices, since they're special for manipulation

Pybullet robot tweaks

---

scripts/supercloud/run_loft_experiments.sh
src/nsrt_learning/strips_learning/clustering_learner.py
src/settings.py
tests/approaches/test_nsrt_learning_approach.py
tests/nsrt_learning/strips_learning/test_clustering_learner.py

implement ClusterAndSearchSTRIPSLearner (LOFT)

---

src/envs/pybullet_blocks.py
src/envs/pybullet_env.py
src/envs/pybullet_robots.py
tests/envs/test_pybullet_blocks.py
tests/envs/test_pybullet_robots.py

another step toward addressing #705

convert pybullet env joint actions to absolute values 

---

src/envs/pybullet_env.py
src/envs/pybullet_robots.py
tests/envs/test_pybullet_blocks.py
tests/envs/test_pybullet_robots.py

change pybullet env action space to joint positions, move IK into options

---

scripts/create_classification_plots.py

example:
https://user-images.githubusercontent.com/26547725/163830796-6ac58cc8-43f6-4c09-928c-35fb95c18d64.mp4

2D classification plot is now video

---

src/envs/blocks.py
src/envs/pybullet_blocks.py
src/envs/pybullet_cover.py
src/envs/pybullet_robots.py
tests/envs/test_pybullet_blocks.py
tests/envs/test_pybullet_robots.py

make open/closed fingers be part of pybullet_robots.py

---

scripts/supercloud/run_action_policy_experiments.sh
src/approaches/interactive_learning_approach.py
src/main.py
src/settings.py
tests/approaches/test_interactive_approach.py

Greedy explore

---

src/utils.py
tests/test_utils.py

(the main logic test is in the assertion at the end of the function)

rotate rectangle about point

---

src/planning.py

this doesn't seem to make a difference in our existing environments (but we should supercloud it). i verified that it makes a huge difference in the stick point environment that's under development though.

special case null samplers during planning

---

scripts/create_classification_plots.py

example:
https://user-images.githubusercontent.com/2816502/164343589-61888d98-b4c0-4e4b-9288-64393716383c.mp4
before this change, the colormap on the right would change on every frame

set limits for stds in classification plots

---

src/nsrt_learning/option_learning.py
src/nsrt_learning/segmentation.py
src/nsrt_learning/strips_learning/base_strips_learner.py
src/nsrt_learning/strips_learning/oracle_learner.py
tests/approaches/test_nsrt_learning_approach.py
tests/nsrt_learning/strips_learning/test_oracle_learner.py
tests/nsrt_learning/test_segmentation.py

fix oracle strips learning when options are unknown

---

src/envs/pybullet_env.py

disable preview windows in pybullet rendering

---

src/settings.py

this seems to help stick point with learned options

env-specific `max_num_steps_option_rollout`

---

src/envs/stick_point.py
src/settings.py
tests/approaches/test_oracle_approach.py
tests/envs/test_stick_point.py

example:
https://user-images.githubusercontent.com/2816502/164981509-be8036f0-2043-422b-8559-d7bee4f711ff.mp4

add flag to disable angles in stick point env

---

src/approaches/base_approach.py
src/approaches/gnn_approach.py
src/approaches/interactive_learning_approach.py
src/approaches/nsrt_learning_approach.py
src/args.py
src/utils.py
tests/approaches/test_gnn_policy_approach.py
tests/test_main.py
tests/test_utils.py

closes #783 
example usage:
```
python src/main.py --env stick_point --min_perc_data_for_nsrt 1 --segmenter oracle --num_train_tasks 1000 --timeout 300 --seed 456 --load_experiment_id direct_bc_1000 --experiment_id direct_bc_max_samp1_1000 --approach nsrt_learning --option_learner direct_bc --sesame_max_samples_per_step 1 --load_a --load_d
```

implement `load_experiment_id` flag

---

tests/approaches/test_gnn_policy_approach.py

trying to fix flakiness in the GNN policy unit test

make gnn policy test less flakey

---

src/approaches/gnn_policy_approach.py

try once more to fix flakey tests

---

src/approaches/gnn_approach.py
src/approaches/gnn_metacontroller_approach.py
src/approaches/gnn_policy_approach.py
src/approaches/nsrt_learning_approach.py
src/nsrt_learning/nsrt_learning_main.py
src/nsrt_learning/sampler_learning.py
tests/nsrt_learning/test_nsrt_learning_main.py

fix GNN metacontroller w/ learned options by having learn_nsrts_from_data() return segmented_trajs

---

scripts/supercloud/run_option_learning_experiments.sh
scripts/supercloud/run_predicators_evalonly_experiments.sh
scripts/supercloud/run_predicators_main_experiments.sh
scripts/supercloud/run_predicators_num_demos_experiments.sh
src/approaches/gnn_option_policy_approach.py
src/settings.py
tests/approaches/test_base_approach.py
tests/approaches/test_gnn_option_policy_approach.py

rename gnn_policy to gnn_option_policy

---

src/ground_truth_nsrts.py
src/main.py
tests/test_main.py

dont pass in env options to approach when learning options

---

tests/nsrt_learning/strips_learning/test_gen_to_spec_learner.py

Test rohan's keep effect induction code on the machine test case to verify understanding that it should fail!

Keep effects machine test

---

scripts/skeleton_score_analysis.py
src/approaches/grammar_search_invention_approach.py
src/nsrt_learning/strips_learning/__init__.py
src/nsrt_learning/strips_learning/base_strips_learner.py
src/predicate_search_score_functions.py
tests/nsrt_learning/strips_learning/test_base_strips_learner.py
tests/nsrt_learning/strips_learning/test_clustering_learner.py
tests/nsrt_learning/strips_learning/test_gen_to_spec_learner.py
tests/nsrt_learning/strips_learning/test_oracle_learner.py
tests/nsrt_learning/test_option_learning.py

* only place it is True within `src/` is `nsrt_learning_main.py`
* but we generally want it to be True for unit tests as well, so that errors don't get swept under the rug
closes #814

make verify_harmlessness NOT have a default

---

scripts/supercloud/run_option_learning_experiments.sh
src/nsrt_learning/segmentation.py
tests/nsrt_learning/test_segmentation.py

after fumbling around with this for a long time, I have pretty low confidence in this general approach. I know that this will not work with `pybullet_blocks`, or at least it will not lead to the oracle operators. but I'm punting on that for now...

contact-based segmentation

---

src/envs/stick_button.py
src/ground_truth_nsrts.py
tests/envs/test_stick_button.py

make stick env touchless

---

src/main.py
src/utils.py
tests/test_utils.py

catch environment failures in run policy

---

src/envs/pybullet_robots.py

use `setJointMotorControlArray` instead of `setJointMotorControl2`

---

src/envs/pybullet_env.py
src/envs/pybullet_robots.py
src/settings.py
tests/envs/test_pybullet_blocks.py
tests/envs/test_pybullet_cover.py
tests/envs/test_pybullet_robots.py

reset control mode for pybullet robots

---

src/envs/cover.py
src/ground_truth_nsrts.py
src/settings.py
src/teacher.py
tests/approaches/test_oracle_approach.py
tests/envs/test_cover.py

hooray for deleting code. we haven't been using the options I'm deleting for a while.

remove the non-learned-equivalent options from cover multistep options

---

src/utils.py
tests/test_utils.py

closes https://github.com/Learning-and-Intelligent-Systems/predicators/issues/876

fix video monitor render order bug

---

src/envs/pybullet_blocks.py
src/envs/pybullet_cover.py
src/envs/pybullet_env.py
src/envs/pybullet_robots.py
tests/envs/test_pybullet_robots.py

closes #881 
should have no functional change.

refactor controllers into utility functions

---

src/ml_models.py
src/nsrt_learning/sampler_learning.py
src/settings.py
tests/approaches/test_nsrt_learning_approach.py
tests/test_ml_models.py

I'm not sure if we will end up using this, but I'm using it to debug sampler learning in the doors environment.

implement degenerate distribution regressor

---

tests/approaches/test_nsrt_learning_approach.py
tests/approaches/test_nsrt_rl_approach.py
tests/approaches/test_oracle_approach.py
tests/nsrt_learning/test_segmentation.py
tests/test_main.py
tests/test_predicate_search_score_functions.py

our tests got very slow recently (up to 140 seconds), oops. this brings us back down to around 90 seconds.

speed up tests

---

scripts/plotting/create_option_learning_plots.py
src/utils.py

also note minor yapf changes on a file from a recent PR

updates to option plotting script

---

requirements.txt
src/approaches/gnn_metacontroller_approach.py
src/approaches/gnn_option_policy_approach.py
src/envs/behavior_options.py
src/envs/blocks.py
src/envs/cluttered_table.py
src/envs/cover.py
src/envs/pybullet_env.py
src/envs/pybullet_robots.py
src/gnn/gnn_utils.py
src/ml_models.py
src/utils.py

upgrade numpy version, remove old `type: ignore`s

---

src/args.py
src/settings.py
tests/approaches/test_nsrt_learning_approach.py
tests/approaches/test_nsrt_rl_approach.py
tests/nsrt_learning/test_option_learning.py
tests/test_main.py

simplifying changes to settings.py

---

src/utils.py
tests/test_utils.py

nostdout() utility

---

scripts/plotting/create_option_learning_plots.py
scripts/supercloud/run_option_learning_experiments.sh
src/envs/coffee.py
src/ground_truth_nsrts.py
src/nsrt_learning/segmentation.py
src/settings.py
tests/approaches/test_oracle_approach.py
tests/envs/test_coffee.py
tests/nsrt_learning/test_segmentation.py

closes #859 
NSRT learning looks good, but I'm not sure yet about option learning. we can do an initial review and tweak later if needed.
PyBulletification is coming soon. in the meantime, here are some crude renderings:
```python src/main.py --env coffee --approach oracle --seed 0 --coffee_render_dpi 150 --video_fps 10 --make_test_videos```
* https://user-images.githubusercontent.com/2816502/169549775-dcd4d013-e64c-4da7-98f4-87d3f3bcea75.mp4
* https://user-images.githubusercontent.com/2816502/169550071-4d328c0c-2a32-4840-a146-047f0b19d2ab.mp4
* https://user-images.githubusercontent.com/2816502/169550497-7f36c18d-e632-4591-af1a-882b9c3afaa2.mp4

coffee environment

---

supercloud.md

supercloud readme updates

---

src/envs/coffee.py
src/ground_truth_nsrts.py
src/nsrt_learning/segmentation.py
src/settings.py
tests/envs/test_coffee.py

examples:
* https://user-images.githubusercontent.com/2816502/169886722-3067237e-cc42-4676-829a-82d93e939204.mp4
* https://user-images.githubusercontent.com/2816502/169886745-a148209f-971f-414d-8f0e-6507d1136c7b.mp4
* https://user-images.githubusercontent.com/2816502/169886753-c2299a43-90e7-4b7f-b3ae-752d6f70c7b9.mp4

add jug twisting to coffee environment

---

src/utils.py
tests/test_utils.py

it's helpful for view cone stuff, which we need in the satellite domain

add Triangle Geom2D

---

scripts/supercloud/run_predicators_sidelining_experiments.sh
src/nsrt_learning/strips_learning/base_strips_learner.py
src/nsrt_learning/strips_learning/gen_to_spec_learner.py
tests/nsrt_learning/strips_learning/test_gen_to_spec_learner.py

subsumes and closes #958
**Supercloud Results**
```Git commit hashes seen in results/:
f6f03e7932e315786326958740d6cdf14acc0f25
NUM_TRAIN_TASKS    NUM_SOLVED AVG_NUM_PREDS AVG_TEST_TIME   AVG_NODES_CREATED  LEARNING_TIME  NUM_SEEDS
EXPERIMENT_ID                                                                                                                                            
painting_backchaining_10demo                         10.00 (0.00)  41.90 (3.91)  14.00 (0.00)   0.47 (0.20)    1995.81 (935.53)   51.47 (2.46)         10
painting_backchaining_25demo                         25.00 (0.00)  49.20 (1.17)  14.00 (0.00)   0.38 (0.08)    2378.04 (829.09)   54.96 (1.76)         10
painting_backchaining_50demo                         50.00 (0.00)  49.40 …
```

[sidelining] remove specialization

---

src/structs.py

i keep forgetting to run docformatter

fix rohan being stupid

---

src/structs.py
src/utils.py
tests/test_structs.py

starting to work towards reimplementing PG3 in this code base.

lifted decision list data structures

---

scripts/evaluate_interactive_approach_entropy.py
src/approaches/interactive_learning_approach.py
src/ml_models.py

fix mypy errors

---

src/structs.py
src/utils.py
tests/test_structs.py

I forgot that in PG3, we importantly allowed negative preconditions.

add negative preconditions to LDL

---

src/nsrt_learning/strips_learning/gen_to_spec_learner.py
tests/nsrt_learning/strips_learning/test_gen_to_spec_learner.py

[sidelining] simplifies code by removing general pnad dict

---

src/approaches/nsrt_rl_approach.py

try to fix flaky NSRT RL test

---

src/envs/behavior.py
src/ground_truth_nsrts.py

Generalizes behavior types so we don't have to learn a separate operator for every single book.
This change also allows us to get rid of a previously-complicated function!

[BEHAVIOR] Behavior type generalization

---

src/envs/coffee.py
src/envs/stick_button.py
src/settings.py
tests/envs/test_coffee.py
tests/envs/test_stick_button.py

inspired by and closes #950
supercloud results AFTER:
```
50ac6440575d9b2841f43a3070691181169a4e03
NUM_TRAIN_TASKS    NUM_SOLVED AVG_NUM_PREDS  AVG_TEST_TIME AVG_NODES_CREATED    LEARNING_TIME  NUM_SEEDS
EXPERIMENT_ID
coffee_main_1000                   1000.00 (0.00)  40.50 (2.58)  12.00 (0.00)   27.76 (5.69)     43.60 (19.12)  1000.55 (19.05)         10
cover_multistep_options_main_1000  1000.00 (0.00)  49.70 (0.64)   5.00 (0.00)    2.09 (2.96)       7.15 (0.42)    371.53 (4.80)         10
doors_main_1000                    1000.00 (0.00)  49.30 (0.78)   7.00 (0.00)    1.14 (0.18)      40.45 (4.81)    488.66 (8.26)         10
stick_button_main_1000             1000.00 (0.00)  41.00 (2.57)   6.00 (0.00)  60.69 (11.03) …
```

remove EnvironmentFailure from stick_button and coffee envs

---

src/envs/pddl_env.py
tests/envs/test_pddl_env.py

verified that PG3 still works fine, and that this doesn't get hit when a random option is chosen, only a random action
closes #1045

fix random actions approach in pddl envs

---

mypy.ini
requirements.txt
src/envs/pddl_env.py
src/ground_truth_nsrts.py
tests/envs/test_pddl_env.py

implement type inheritance for pddl envs

---

src/envs/assets/pddl/forest/domain.pddl
src/envs/pddl_env.py
src/envs/pddl_procedural_generation.py
src/settings.py
tests/envs/test_pddl_env.py
tests/envs/test_pddl_procedural_generation.py

coauthored by @Abraham-Mitchell and based on original code by @ryangpeixu

forest domain from PG3 paper

---

src/envs/behavior.py
src/envs/behavior_options.py
src/ground_truth_nsrts.py

The main changes here are:
- The `reachable` predicate now has 1 arity instead of 2. The agent is no longer a parameter of this predicate (this was causing issues because of our assumption during backchaining that all preconditions must have the same params as the add effects and option).
- Held objects are no longer `reachable` (i.e, `holding` and `reachable` are no longer simultaneously True). This was previously causing needlessly-complicated operators because of getting the precondition by intersection.
- The `navigateTo` sampler has been updated to sample within minimum and maximum radii.
All other changes follow from these.
These changes enable us to learn the following operators from 5 demos:
```
STRIPS-Grasp-hardback0:
Parameters: [?x0:hardback]
Preconditions: [handempty(), …
```

Changing BEHAVIOR predicates and gt NSRTS for backchaining to work.

---

src/approaches/gnn_action_policy_approach.py
src/approaches/gnn_approach.py
src/approaches/gnn_option_policy_approach.py
src/approaches/nsrt_metacontroller_approach.py

this will be used by a forthcoming LLM approach

add optional memory dict to nsrt metacontroller

---

src/nsrt_learning/strips_learning/base_strips_learner.py
src/planning.py

specifically, we want to reuse the main logic in the open-loop LLM approach to turn the option plan output by the LLM into ground NSRT
@NishanthJKumar please check carefully that I didn't change the functionality

refactor core harmlessness check for later reuse

---

.gitignore
requirements.txt
src/llm_interface.py
src/settings.py
tests/test_llm_interface.py

large language model interface

---

src/utils.py
tests/test_utils.py

handle lowercase special values in flag overrides

---

.gitignore
requirements.txt
scripts/openstack/README.md
scripts/openstack/configs/example.yaml
scripts/openstack/download.py
scripts/openstack/launch.py

because supercloud is continuing to be difficult!!!!
see the README and file docstrings for info.

scripts for using openstack cluster

---

src/approaches/bilevel_planning_approach.py
src/approaches/pg4_approach.py
tests/approaches/test_pg3_approach.py

this fixes the fact that pg4 was not previously logging metrics like we want it to, and also removes some redundant code between pg4 and bilevel planning approach.

refactor pg4 and bilevel planning

---

mypy.ini
requirements.txt
scripts/analyze_results_directory.py
scripts/evaluate_interactive_approach_classifiers.py
scripts/launch_slack_bot.py
scripts/openstack/launch.py
scripts/plotting/create_option_learning_plots.py

Tested by running `scripts/plotting/create_bar_plots.py` on RLDM experiments from Dropbox and `scripts/plotting/create_option_learning_plots.py` on option learning experiments from Dropbox. Also tried `scripts/analyze_results_directory.py` on each.
closes #973 
reverts #1069

fix mypy pandas stubs and re-enable mypy checking for `scripts/`

---

src/planning.py
tests/test_planning.py

see the new comment for justification. this is important for @Alchemy5 's code and I suspect that it will also improve @wester-is-not-real 's results.
@wester-is-not-real  -- we should regenerate the pg4 results after this is merged.

change cost of policy-generated actions to zero in sesame

---

src/approaches/bilevel_planning_approach.py

makes #1097 a bit easier to review, and anyway is a good idea

pull out metrics saving in bilevel_planning_approach.py

---

src/planning.py
tests/approaches/test_pg4_approach.py

revert visited skeleton assertion in guided sesame

---

src/planning.py

fixes for `visited_skeletons` in planning.py

---

src/approaches/llm_bilevel_planning_approach.py
src/approaches/llm_open_loop_approach.py
tests/approaches/test_llm_open_loop_approach.py

rename open loop llm to llm open loop

---

src/approaches/pg3_approach.py
src/planning.py
tests/approaches/test_pg3_approach.py

before this change, this crashed:
```python src/main.py --env cluttered_table --approach pg3 --seed 0 --experiment_id cluttered-table-pg3 --strips_learner oracle --sampler_learner oracle --num_train_tasks 5```

fix pg3 crash on discovered failures

---

src/approaches/pg3_approach.py

we were accidentally starting the search for online PG3 with the old policy, which could use outdated NSRTs

fix initialization in online pg3

---

src/approaches/online_pg3_approach.py
src/approaches/pg3_approach.py

relearn online PG3 generalized policy only if NSRTs change

Online Learning Cycle Stoppage

---

src/approaches/pg3_approach.py

load NSRTs in pg3/4 approaches

---

scripts/cluster_utils.py
scripts/configs/example_basic.yaml
scripts/configs/example_multiple_combinations.yaml
scripts/configs/llm_pddl.yaml
scripts/configs/pg3_offline.yaml
scripts/configs/pg3_online.yaml
scripts/configs/pg4.yaml
scripts/local/launch.py
scripts/openstack/launch.py
scripts/supercloud/launch.py

change the way branches are handled in launches

---

scripts/configs/llm_pddl_ablations.yaml

results: https://docs.google.com/spreadsheets/d/11jM4G_jkk6owaieerXif3cakK57Tu9BLyLdLAeMFyKY/edit#gid=838614637

config for llm analysis questions 1 and 2

---

src/envs/pybullet_blocks.py
src/envs/pybullet_cover.py
src/envs/pybullet_robots.py
src/pybullet_helpers/controllers.py
src/pybullet_helpers/inverse_kinematics.py
src/pybullet_helpers/robots/single_arm.py
tests/envs/test_pybullet_robots.py

Move Pybullet Controllers + IK using the IDE.
Didn't move the motion planning and getting kinematic chain to keep the diff relatively small. So that will be the next PR and will be pretty quick to do.
Will fix up tests and moving into their respective places when patching in my commits from the `panda-willshen-cleanup` branch.

Pybullet Controllers + IK

---

src/pybullet_helpers/motion_planning.py
src/pybullet_helpers/robots/single_arm.py
src/pybullet_helpers/utils.py
tests/envs/test_pybullet_robots.py

- Using IDE functionality
Next:
- Start merging in my big code changes
- Along with unit tests (the big one Tom previously mentioned that just checks things run properly)
- Refactor so it's more neatly tied with Rachel's real robot API

Move remaining Pybullet code to dedicated modules

---

src/planning.py

fix keywords to parse from fd output

---

scripts/run_checks.sh

updates run_checks script to match new repo re-org

Update run_checks script

---

scripts/plotting/create_interactive_predicate_learning_plots.py

- experiment IDs were out-of-date
- also change the color of one line to be more distinguishable

Update interactive experiment plotting script

---

scripts/supercloud/submit_supercloud_job.py

Fix supercloud launch command

---

predicators/approaches/gnn_option_policy_approach.py
predicators/approaches/llm_bilevel_planning_approach.py
predicators/approaches/nsrt_learning_approach.py
predicators/approaches/pg3_approach.py
predicators/gnn/gnn_utils.py
predicators/main.py
predicators/planning.py
predicators/predicate_search_score_functions.py
predicators/third_party/fast_downward_translator/timers.py
predicators/utils.py
scripts/grammar_search_analysis.py
tests/test_ml_models.py

change all `time.time()` to `time.perf_counter()`

---

scripts/launch_slack_bot.py

fix slackbot to use interactive bash during launch

---

predicators/approaches/pg3_approach.py

refactor pg3 policy search initialization

---

scripts/configs/backchaining_predicate_invention.yaml

@NishanthJKumar I figure we should try just predicate invention + backchaining before we also try option learning. does this look right to you?

backchaining predicate invention yaml

---

setup.py

Switch lisdf dependency from git to pypi

---

scripts/configs/pg4.yaml

Test is in the painting environment with box, shelf, and box lid as objects.

Added new test in the pg4.yaml config. 

---

predicators/nsrt_learning/option_learning.py
predicators/settings.py
tests/nsrt_learning/test_option_learning.py

what I want to be able to do is learn options in a 4D space (x y z gripper position, fingers) instead of the full action space in the pybullet environments (which is 9D right now). this PR is a first step toward that. the next step will be to implement an action space converter that actually does something.

action conversion for option learning

---

scripts/cluster_utils.py
scripts/configs/backchaining_predicate_invention.yaml
scripts/configs/example_basic.yaml
scripts/configs/example_multiple_combinations.yaml
scripts/configs/full_pipeline.yaml
scripts/configs/interactive_learning.yaml
scripts/configs/llm_pddl.yaml
scripts/configs/nightly.yaml
scripts/configs/pg3_offline.yaml
scripts/configs/pg3_online.yaml
scripts/configs/pg4.yaml

make FLAGS and ARGS optional for envs and approachs in yaml configs

---

scripts/evaluate_interactive_approach_classifiers.py

Remove flaky test from held out `Covers` classifier test states

Interactive learning: Remove flaky classifier test

---

tests/approaches/test_nsrt_learning_approach.py

Fixed the long NSRT learning test by making it a longrun.

Addressed long pytest in NSRT learning approaches

---

supercloud.md

update supercloud readme to use new launch and download scripts

---

predicators/approaches/oracle_approach.py
predicators/datasets/demo_replay.py
predicators/ground_truth_nsrts.py
predicators/nsrt_learning/sampler_learning.py
predicators/nsrt_learning/segmentation.py
predicators/nsrt_learning/strips_learning/oracle_learner.py
tests/approaches/test_initialized_pg3_approach.py
tests/approaches/test_oracle_approach.py
tests/approaches/test_pg3_approach.py
tests/approaches/test_pg4_approach.py
tests/explorers/test_base_explorer.py
tests/explorers/test_exploit_bilevel_planning_explorer.py
tests/explorers/test_glib_explorer.py
tests/explorers/test_greedy_lookahead_explorer.py
tests/nsrt_learning/test_option_learning.py
tests/test_planning.py
tests/test_utils.py

we should've always done this, and now I need it for another forthcoming PR

use env argument in get_gt_nsrts instead of CFG.env

---

predicators/approaches/initialized_pg3_approach.py
predicators/args.py
predicators/planning.py
predicators/settings.py
tests/approaches/test_initialized_pg3_approach.py

modified from code by @ryangpeixu

create and apply analogy to initialize PG3

---

predicators/nsrt_learning/option_learning.py
predicators/pybullet_helpers/controllers.py
predicators/pybullet_helpers/robots/single_arm.py
tests/pybullet_helpers/robots/test_panda.py
tests/pybullet_helpers/test_pybullet_robots.py

closes #1285
this is a pretty ham-fisted fix. I tried to change the controller in a way that would restore performance for both robots without anything case-based, but ran out of patience.

fix fetch regression

---

predicators/envs/blocks.py
predicators/settings.py
tests/approaches/test_oracle_approach.py
tests/envs/test_blocks.py

example:
```python predicators/main.py --env pybullet_blocks --approach oracle --seed 0 --use_gui --blocks_holding_goals True --blocks_num_blocks_test '[1]'```

flag to use holding-only goals in blocks

---

predicators/approaches/pg3_approach.py
predicators/settings.py
tests/approaches/test_pg3_approach.py

setting this flag to False makes the branching factor much lower, and so the search over policies much faster, but I'm not sure if we can get away with it in general, so defaulting to True.

add flag for pg3 add condition operator fresh var creation

---

predicators/nsrt_learning/strips_learning/pnad_search_learner.py

Previously, our `recompute_pnads_from_effects` function would directly mutate underlying PNAD objects. This would change the state of previously-achieved nodes in hill-climbing, which is EXTREMELY unsafe (I frankly have no clue how our tests were passing...). This PR ensures that recomputing PNADs also *copies* them.

fixes egregious pnad copying bug

---

predicators/envs/repeated_nextto.py

This is necessary/useful to show a significant difference between PNAD search learner and the backchaining learner.

Makes RNT ambiguous much harder in terms of generalization from training to test

---

predicators/approaches/pg3_approach.py
tests/approaches/test_pg3_approach.py

PG3 operators that creates candidate rules by deleting conditions

delete condition search operator

---

scripts/lisdf_pybullet_executor.py
scripts/run_blocks_real.sh

this is getting embarrassingly hacky and redundant, but that's a problem for future Tom

LISDF visualizer script

---

.gitignore
.predicators_pylintrc
mypy.ini
scripts/realsense_helpers.py
scripts/run_blocks_perception.py
scripts/run_blocks_real.sh

`realsense_helpers.py` is a pared down version of code by @williamshen-nz

add image capture from realsense cameras to real blocks pipeline

---

predicators/planning.py

change FD installation documentation to use upstream source

---

predicators/structs.py
predicators/utils.py

these are also present in https://github.com/tomsilver/pg3/

fix some typos in comments

---

predicators/ground_truth_nsrts.py
predicators/utils.py
scripts/supercloud/run_ignore_effects_experiments.sh

Changes necessary to get LOFT with replays working on domains for IJCAI 2023 paper.
Also modifies ignore effects experiments bash script to only run relevant experiments!

Changes for envs for LOFT with replays

---

predicators/envs/touch_point.py
predicators/ground_truth_nsrts.py
tests/approaches/test_oracle_approach.py
tests/envs/test_touch_point.py

Adds another touch point environment that is (1) parameterized and (2) has a 2D action space. The intention is to use is to debug the simplest cases for learning nsrts via reinforcement learning.

Add new environment: a parameterized touch point with 2D action space.

---

predicators/envs/playroom.py
predicators/ground_truth_nsrts.py
tests/envs/test_playroom.py

another version of the simple playroom env where each block has a "clear" attribute so we can learn all predicates with the assumption that they are a function of only their argument's states

`PlayroomEnv` variant

---

predicators/approaches/pg3_approach.py
predicators/structs.py
tests/approaches/test_initialized_pg3_approach.py
tests/test_structs.py
tests/test_utils.py

closes #1383
to be merged after #1384

fix `initialized_pg3` approach following outsourcing of pg3 

---

predicators/envs/pybullet_env.py
predicators/pybullet_helpers/camera.py
predicators/pybullet_helpers/motion_planning.py
scripts/lisdf_pybullet_visualizer.py
scripts/run_blocks_perception.py
tests/pybullet_helpers/test_motion_planning.py
tests/pybullet_helpers/test_pybullet_robots.py

and a new test that finds motion plans like this:
https://user-images.githubusercontent.com/2816502/219951611-848b3b7f-1f61-4382-826c-713df790879b.mov
the new test takes about 0.7 seconds.

a few improvements to pybullet motion planning

---

scripts/configs/interactive_learning.yaml
scripts/plotting/create_classification_plots.py

- add playroom experiments to config
- plot entropies, not stds, in heatmap figures

Active Predicate Learning: Last code changes

---

predicators/envs/doors.py
predicators/ground_truth_models/doors/__init__.py
predicators/ground_truth_models/doors/options.py
predicators/utils.py
tests/envs/test_doors_env.py

also move the caches into the simulator state (see `utils.StateWithCache`)

move options out of doors environment 

---

predicators/approaches/pg3_approach.py
tests/approaches/test_pg3_approach.py

initialize pg3 from file

---

predicators/envs/cover.py
predicators/envs/pybullet_cover.py
predicators/envs/pybullet_env.py
predicators/ground_truth_models/cover/__init__.py
predicators/ground_truth_models/cover/options.py

I forgot about these. after these, hopefully only the pybullet ones remain

moving ground-truth options for a few more cover envs 

---

predicators/envs/sokoban.py

also fix spatial predicates so that they only apply to location objects

sokoban object tracking

---

predicators/envs/painting.py
predicators/envs/repeated_nextto_painting.py
tests/envs/test_painting.py

example:
https://user-images.githubusercontent.com/2816502/228660977-57e2738b-6e2a-471c-8bf5-bb2de49ccd90.mp4
pretty crappy but it gets the job done

add demo collection interface for painting

---

predicators/envs/exit_garage.py
predicators/ground_truth_models/exit_garage/__init__.py
predicators/ground_truth_models/exit_garage/nsrts.py
predicators/ground_truth_models/exit_garage/options.py
predicators/refinement_estimators/oracle_refinement_estimator.py
predicators/settings.py
predicators/utils.py
tests/approaches/test_oracle_approach.py
tests/envs/test_exit_garage.py
tests/refinement_estimators/test_oracle_refinement_estimator.py
tests/test_utils.py

**Summary of changes:**
- Implemented environment `exit_garage` and associated options, nsrts, tests
- Implemented "oracle" refinement estimator for `exit_garage` that prioritizes removing all obstacles
- Extended BiRRT implementation to an RRT class that parents BiRRT
`exit_garage` **environment**
In `exit_garage`, a non-holonomic car attempts to drive to the exit of a cluttered garage with a variable number of obstacles. A ceiling-mounted robot can be used to pick up obstacles and/or move them to a separate storage area.
The following command can be used to get successful test videos:
`python predicators/main.py --env exit_garage --approach refinement_estimation --refinement_estimator oracle --seed 0 --num_test_tasks 5 --make_test_videos --timeout 60`

exit_garage environment

---

predicators/nsrt_learning/segmentation.py
tests/nsrt_learning/test_segmentation.py

I need this for painting in online bridge learning from human demos
- segmenting from options doesn't work because we don't have options in human demos
- atom changes doesn't work because nothing changes when the box lid is opened

add segmentation strategy that segments at every step

---

predicators/approaches/grammar_search_invention_approach.py

Adds this to metrics; useful as we begin implementing new methods that attempt to speed up predicate invention!

Logs num predicate evals during predicate invention

---

predicators/ml_models.py
tests/test_ml_models.py

before the change, the unit test would crash with an assertion error

fix classifier predict_proba in case where there is 1 class

---

predicators/envs/cover.py
predicators/ground_truth_models/cover/__init__.py
predicators/ground_truth_models/cover/nsrts.py
predicators/ground_truth_models/cover/options.py
predicators/planning.py
predicators/settings.py
tests/approaches/test_active_sampler_learning_approach.py
tests/approaches/test_oracle_approach.py
tests/envs/test_cover.py

examples:
```
python predicators/main.py --env regional_bumpy_cover --approach oracle --seed 0 --make_test_videos --num_test_tasks 10
```
https://github.com/Learning-and-Intelligent-Systems/predicators/assets/2816502/a8b12439-f261-4b47-b624-62b0e1b4dace
https://github.com/Learning-and-Intelligent-Systems/predicators/assets/2816502/8a49dc70-bd2d-4656-9a0c-4ddb1217d04b
https://github.com/Learning-and-Intelligent-Systems/predicators/assets/2816502/281bc2d6-e294-4317-8a20-e98eb9cbceea

regional bumpy cover environment

---

scripts/configs/active_sampler_learning.yaml
scripts/plotting/create_active_sampler_learning_plots.py

add more yamls for active sampler learning experiments

---

predicators/approaches/active_sampler_learning_approach.py
predicators/ml_models.py
predicators/settings.py
predicators/utils.py
scripts/configs/active_sampler_learning.yaml
scripts/plotting/create_active_sampler_learning_plots.py
tests/approaches/test_active_sampler_learning_approach.py

also add KNN classifier in addition to MLP classifier

manual feature selection for active sampler learning

---

predicators/explorers/active_sampler_explorer.py
tests/explorers/test_active_sampler_explorer.py

and eventually give up if none are reachable

active sampler explorer: consider multiple goals in case one is not reachable

---

scripts/configs/kitchen_active_learning.yaml
scripts/plotting/create_active_sampler_learning_plots.py

pretty ugly, but I think it's stable enough that we can move on to adding other skills in the kitchen environment

add knob to kitchen config

---

predicators/envs/kitchen.py

remove unnecessary rendering from kitchen

---

scripts/analyze_results_directory.py

a recent update to pandas was causing a crash, this fixes it

small fix to analysis script

---

predicators/envs/kitchen.py
predicators/ground_truth_models/kitchen/nsrts.py
predicators/ground_truth_models/kitchen/options.py
tests/envs/test_kitchen.py

This PR adds policies and tests for the MoveToPrePull and Pull  Kettle nsrts.

Kitchen Kettle Reverse by Pulling

---

predicators/envs/kitchen.py
predicators/ground_truth_models/kitchen/nsrts.py
predicators/ground_truth_models/kitchen/options.py
tests/envs/test_kitchen.py

Tweaks some tolerances and parameters to make Pushing and Pulling options work one after the other.

Continuous Pushing and Pulling Test

---

scripts/plotting/create_active_sampler_learning_plots.py

minor plotting updates

---

predicators/envs/kitchen.py
predicators/ground_truth_models/kitchen/nsrts.py
predicators/ground_truth_models/kitchen/options.py
tests/envs/test_kitchen.py

This PR adds Opening and Closing nsrts for all hinge doors.

Microwave Push Open and Close

---

predicators/explorers/active_sampler_explorer.py
predicators/utils.py
scripts/configs/active_sampler_learning.yaml
scripts/plotting/create_active_sampler_learning_plots.py
tests/explorers/test_active_sampler_explorer.py

fall back to random in active sampler explorer

---

predicators/envs/sticky_table.py
predicators/ground_truth_models/sticky_table/__init__.py
predicators/ground_truth_models/sticky_table/nsrts.py
predicators/ground_truth_models/sticky_table/options.py
predicators/settings.py
tests/envs/test_sticky_table.py

example:
```
python predicators/main.py --env sticky_table --approach oracle --num_test_tasks 10 --num_train_tasks 0 --seed 0 --bilevel_plan_without_sim True --debug --execution_monitor expected_atoms --make_test_videos
```
https://github.com/Learning-and-Intelligent-Systems/predicators/assets/2816502/113d4056-ef0b-4864-8c69-a928b6f00c16
https://github.com/Learning-and-Intelligent-Systems/predicators/assets/2816502/de7aec2d-08b9-4bda-a947-3eac511a2161

simulated sticky table environment

---

predicators/approaches/active_sampler_learning_approach.py
predicators/explorers/__init__.py
predicators/explorers/active_sampler_explorer.py
predicators/settings.py
scripts/plotting/analyze_competence_data.py
tests/explorers/test_active_sampler_explorer.py

no functional change yet. just setting the stage for extrapolating competences soon.

track and analyze skill competence over active sampler learning cycles

---

predicators/envs/sticky_table.py
predicators/ground_truth_models/sticky_table/nsrts.py

also bite the bullet and introduce test task distribution shift

fix edge case in sticky table sim

---

predicators/approaches/maple_q_approach.py

for consistency with active learning approach

add geometric scheduling to maple q

---

predicators/utils.py
scripts/cluster_utils.py
setup.py
tests/envs/test_base_env.py

Version bump raised in issue #1567

MyPy version bump

---

predicators/approaches/bilevel_planning_approach.py
predicators/approaches/bridge_policy_approach.py
predicators/approaches/oracle_approach.py
predicators/option_model.py
tests/approaches/test_oracle_approach.py
tests/explorers/test_active_sampler_explorer.py
tests/explorers/test_base_explorer.py
tests/explorers/test_exploit_bilevel_planning_explorer.py
tests/explorers/test_glib_explorer.py
tests/explorers/test_greedy_lookahead_explorer.py
tests/test_option_model.py
tests/test_planning.py

minor change, most of the lines are just tests

allow third party users to define their own oracle NSRTs

---

predicators/settings.py
scripts/configs/active_sampler_learning.yaml

Hyperparam changes to create prettier grid row graphs

---

.coveragerc
tests/approaches/test_pg3_analogy_approach.py
tests/envs/test_pybullet_cover.py

I finally got fed up with this enough to do something about it
Closes #1324

disable flakey tests

---

README.md

remove dead email and add NJK email in README

---

predicators/main.py
predicators/settings.py
tests/test_main.py

so that we can include approach wrappers as flags in YAML configs

add separate flag for approach wrapper

---

predicators/approaches/active_sampler_learning_approach.py
predicators/settings.py

Useful to get a really good estimate of the exact competences of the various skills!

Add a new flag to enable obsessive task-solving when exploring for the first few cycles

---

predicators/approaches/active_sampler_learning_approach.py

I believe this was unintentionally introduced by #1593 , and undiscovered because we didn't run a large-scale supercloud experiment for a while 🙀

Fix issue with random nsrts approach

---

predicators/explorers/active_sampler_explorer.py
scripts/configs/active_sampler_learning.yaml

```
cada9828a9876217ae926523440ae5d0697e0ef0
NUM_TRAIN_TASKS    NUM_SOLVED AVG_NUM_PREDS AVG_TEST_TIME AVG_NODES_CREATED     LEARNING_TIME   AVG_REF_COST  NUM_SEEDS
EXPERIMENT_ID                                      CYCLE                                                                                                                        
ball_and_cup_sticky_table-planning_progress_exp... 0        50.00 (0.00)   4.80 (1.60)  19.92 (1.95)   0.42 (0.01)      56.52 (5.82)       1.12 (0.08)    0.96 (0.50)          5
1        50.00 (0.00)   3.40 (1.36)  22.56 (2.33)   0.42 (0.02)      64.00 (6.24)     26.34 (48.34)    1.35 (0.54)          5
2        50.00 (0.00)   4.80 (1.17)  20.64 (2.45)   0.46 (0.05)      58.56 (6.56) …
```

add UCB bonus to planning progress explorer

---

predicators/explorers/active_sampler_explorer.py
scripts/configs/active_sampler_learning.yaml
scripts/plotting/create_active_sampler_learning_plots.py
tests/explorers/test_active_sampler_explorer.py

Adds two new important baselines to finish up all approaches we want to compare our approach against for our final experiments.
Also, normalizes the UCB bonus by dividing by the number of test tasks.

Add competence gradient and skill diversity baselines

---

scripts/openstack/README.md
setup.py

More information and instructions (happy to add even more if required; the clearer then probably the better before we forget again!). Also freeze the pytest version, since that was causing weird CI failures.

update reaadme for openstack + freeze pytest version

---

README.md

@NishanthJKumar after we merge this, we can also update the BDAI fork and add the planning to practice reference in that README

update README papers

---

predicators/envs/pybullet_env.py

Remove outdated assertion about using GUI in pybullet videos

---

predicators/approaches/grammar_search_invention_approach.py

RIP - just realized this, but should've caught it earlier!

fix issue where I forgot one of the valid options for predicate invention

---

.gitignore
predicators/envs/kitchen.py
predicators/ground_truth_models/kitchen/nsrts.py
predicators/perception/kitchen_perceiver.py

Modifications to kitchen to include new task that we'll use to debug/test VLM predicate invention.
Also minor modification to gitignore for vscode users.

Adds kettle boiling task to kitchen environment

---

.gitignore
predicators/datasets/generate_atom_trajs_with_vlm.py
predicators/envs/base_env.py
predicators/envs/kitchen.py
predicators/envs/vlm_envs.py
tests/envs/test_cover.py

Specifically, this is tested on Kitchen and should help us debug VLM labelling in this environment more easily.

Implements general interface for specifying 'debug grammar' predicates for environments

---

predicators/envs/kitchen.py
predicators/settings.py
predicators/utils.py

Useful for VLM predicate invention. Note that I didn't test the utils functions I wrote because the only way to verify them is visually, and any test I could think to write was kinda just for the sake of running the code...
https://github.com/Learning-and-Intelligent-Systems/predicators/assets/12446934/b3484303-a3f4-4498-a712-60dea2fffbb9

Adds set-of-marks rendering for burners in the kitchen environment

---

predicators/envs/kitchen.py
predicators/ground_truth_models/kitchen/options.py

Some minor changes that make the light-switch skill more consistent, and also improves the set-of-marks labelling for the VLM

Kitchen minor fixes

---

predicators/approaches/bridge_policy_approach.py
predicators/approaches/maple_q_approach.py
predicators/envs/grid_row.py
predicators/ml_models.py
predicators/settings.py
tests/approaches/test_bridge_policy_approach.py
tests/approaches/test_maple_q_approach.py
tests/envs/test_grid_row.py
tests/test_ml_models.py

Set door position and light levels in grid_row_door to be fixed for consistency across train and test. Note that rl_bridge_approach does not have timeout feature
https://github.com/Learning-and-Intelligent-Systems/predicators/assets/102700848/f762019b-4f37-40d4-9013-c9e87cd02057

Created rl_bridge_approach and rendering for grid_row_door

---

predicators/planning.py

This way we won't need to go on wild goose hunts again hopefully

Adds nicer error message to fd dr-reachability case

---

predicators/approaches/grammar_search_invention_approach.py

All credit to @ashayathalye - closes #1674

Rename geometric predicates to prevent FD from freaking out

---

predicators/envs/kitchen.py
predicators/perception/kitchen_perceiver.py

modify test-time goals for certain tasks in kitchen to make sure they're different from training time

Kitchen goal complexity

---

predicators/approaches/grammar_search_invention_approach.py
tests/approaches/test_grammar_search_invention_approach.py

This is the implementation for a baseline that just uses all the proposed predicates instead of trying to subselect!

No grammar search vlm invention baseline

---

predicators/pretrained_model_interface.py
predicators/utils.py
tests/test_pretrained_model_interface.py

Fixes + QoL improvements to the pretrained model interface

---

scripts/run_checks.sh
tests/nsrt_learning/strips_learning/test_llm_strips_learner.py

makes it so that checks don't always fail locally for `llm_strips_learner`

minor fixes to checks

---

predicators/approaches/llm_open_loop_approach.py
predicators/approaches/vlm_open_loop_approach.py
predicators/approaches/vlm_planning_prompts/few_shot.txt
predicators/approaches/vlm_planning_prompts/no_few_shot.txt
predicators/settings.py
predicators/structs.py
predicators/utils.py
tests/test_utils.py

Includes a new VLM-based planning approach [based on recent work](https://arxiv.org/pdf/2311.17842).
TODO's remaining:
1. Add some kind of explanation of what the different continuous parameters are; because otherwise it's kind of hopeless/ludicrous maybe to ask the VLM to output them?
2. Potentially test entire approach.

VLM Open-Loop Approach

---

predicators/approaches/grammar_search_invention_approach.py

A while ago, we introduced a feature that renames certain geo predicates because planners don't like certain characters in geo predicates. However, when creating datasets for learning, we also check that the dataset only contains atoms involving predicates that are in our 'learned' set. Renaming was interfering with this, and making it such that - for certain commands - we'd throw away all our geo predicates when doing NSRT learning and only learn NSRTs over VLM predicates, which breaks a number of baselines.
Try running this command before and after PR to see massive difference in the learned NSRTs.
```
python predicators/main.py --env burger_no_move --approach grammar_search_invention --seed 0 --num_train_tasks 3 --num_test_tasks 1 --bilevel_plan_without_sim True --offline_data_method …
```

Fix bug caused due to predicate renaming

---

predicators/approaches/grammar_search_invention_approach.py
predicators/settings.py
predicators/utils.py
scripts/configs/pred_invention_vlm.yaml
tests/test_utils.py

Remove assertion that was causing some seeds to fail. Also, modify some settings in the yaml to improve performance of grammar search!

Fix experiment bugs

---

predicators/approaches/grammar_search_invention_approach.py
predicators/approaches/nsrt_learning_approach.py
predicators/envs/burger.py
predicators/settings.py
scripts/configs/pred_invention_vlm.yaml

Mostly minor changes that make our approach work in both the `more_stacks` as well as the `fatter_burger` task distributions!

Changes to get our approach working nicely in the `fatter_burger` task distribution!

---

predicators/pybullet_helpers/ikfast/utils.py

old nondeterminism issue, sorry fam

remove np.random.uniform from ikfast utils

---

predicators/datasets/generate_atom_trajs_with_vlm.py
predicators/envs/burger.py
predicators/pretrained_model_interface.py
setup.py

Fix subtle but very consequential bug with the `--vlm_double_check_output` functionality.
Also, update burger command to address #1739 .

Fix pred invent vlm double check
